### PR TITLE
fix(rome_js_analyze): improve the handling of trivia in `useBlockStatements`

### LINKED ISSUE #2943: 🐛 Misaligned code fix for `js/useBlockStatements`
### Environment information

[Playground](https://play.rome.tools/?code=if+%28test%29+%0A++bar&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=false&jsx=true#aQBmACAAKAB0AGUAcwB0ACkAIAAKACAAIABiAGEAcgA=)

### What happened?

Misalignment for 
```
if (test) 
  bar
```

```
Suggested fix: Wrap the statement with a `JsBlockStatement`
    | @@ -1,2 +1,3 @@
0 0 |   if (test)
1   | -   bar
  1 | +   {
  2 | +   bar }
```

### Expected result

```
if (test) {
  bar
}
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

This PR fixes #2943 by introducing additional logic in the code generating the auto-fix for the rule to inspect the tokens and nodes being modified, and move or add trivia pieces accordingly.

I also fixed the query used by the rule to ensure it would trigger separately for if statements and else clauses, ensuring both the consequent and alternate statements would have a diagnostic and code action emitted, and not only the first one visited by the rule.

## Test Plan

I added a number of additional test cases in the snapshot tests for the rule to verify the handling of empty statements in if-else chains and indentation

### CODE REVIEW

File: crates/rome_js_analyze/src/analyzers/js/use_block_statements.rs [hunk 1]
```diff
@@ -191,40 +280,65 @@ impl Rule for UseBlockStatements {
...
 }
 
+/// Collect newline and comment trivia pieces in reverse order up to the first newline included
+fn collect_to_first_newline(trivia: JsSyntaxTrivia) -> Vec<SyntaxTriviaPiece<JsLanguage>> {
+    let mut has_newline = false;
+    trivia
+        .pieces()
+        .rev()
+        .inspect(|piece| {
+            eprintln!("    collect_to_first_newline {piece:?}");
```
Comment (ematipico) [inline crates/rome_js_analyze/src/analyzers/js/use_block_statements.rs:290]: Is this intended?

**Review by ematipico — APPROVED** [review]

File: crates/rome_js_analyze/src/analyzers/js/use_block_statements.rs (hunk 1 above)
Comment (leops) [reply crates/rome_js_analyze/src/analyzers/js/use_block_statements.rs]: Goo catch, that's debugging code I forgot to remove
