### PR TITLE
fix(rome_diagnostics): improve the handling of newline characters in diffs

### LINKED ISSUE #3515: 🐛 Formatter diff not showing removed lines
### Environment information

```bash
main (ac5da792a9897ddcdce05d5c543eb895459600b7)
```

### What happened?

1. Create a test file with the following content:

```javascript
for (; ;) {
}

console.log("test");

```

2. Run `rome format`

```bash
rome format test.js
```

And Rome prints:

```
website/src/test.js format ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ℹ Formatter would have printed the following content:
  
    1 │ for·(;·;)·{
      │       -    

Compared 1 files in 8ms
```

It only highlights the removal of the space between the two `;` but doesn't highlight that the formatter will also put the closing `}` on the same line as the opening `{`

Output after running `rome format test.js --write`

```javascript
website/src/test.js format ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ℹ Formatter would have printed the following content:
  
    1 │ for·(;·;)·{
      │       -    

Compared 1 files in 8ms
```

### Expected result

The diff to show all formatting changes

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

Fixes #3515

This PR changes how line breaks are handled in diffs, and specifically how individual lines get marked as "modified" when a line break is removed or inserted. It fixes an issue with the rendering of diffs from the formatter, but also changes when diffs are allowed to be rendered in short mode as the removal of an entire line is now shown in full mode (with the surrounding lines of context).

## Test Plan

I've added an additional test case for this and updated the ellipsis case since it was actually being rendered incorrectly. I've also improved how markup assertion mismatches are displayed in the tests to ensure these kinds of issue are easier to notice in the future, and update a few snapshots related to the short mode changes.

### CODE REVIEW

File: crates/rome_diagnostics/src/v2/display/diff.rs [hunk 1]
```diff
@@ -134,36 +140,19 @@ fn process_diff_ops<'a, 'diff>(
...
-            None => {
-                // Doesn't contain a newline
-                push_to_line(&mut state, *before_line, *after_line, tag, text, false);
-                continue;
-            }
-        };
-
         // Get all the lines
-        let mut parts = text.split('\n').enumerate();
+        let mut parts = text.split('\n');
```
Comment (MichaReiser) [inline crates/rome_diagnostics/src/v2/display/diff.rs:144]: Nit: `lines`? or is it guaranteed for code frames to never contain windows line breaks?

File: crates/rome_js_analyze/tests/specs/correctness/noDebugger.js.snap [hunk 2]
```diff
@@ -78,8 +79,11 @@ noDebugger.js:9:3 lint/correctness/noDebugger  FIXABLE  ━━━━━━━━
   
   i Suggested fix: Remove debugger statement
   
-    9 │ ··debugger;
-      │ -----------
+     7 7 │   function test() {
+     8 8 │     let a = 3;
+     9   │ - ··debugger;
```
Comment (MichaReiser) [inline crates/rome_js_analyze/tests/specs/correctness/noDebugger.js.snap:84]: I like the new rendering. The additional context helps to understand which line was deleted.

**Review by MichaReiser — APPROVED** [review]

File: crates/rome_diagnostics/src/v2/display/diff.rs (hunk 1 above)
Comment (leops) [reply crates/rome_diagnostics/src/v2/display/diff.rs:144]: It's possible for code frames or diffs to contain windows line breaks but they're handled separately in `print_invisibles`. The reason this code is using `split` instead of `lines` is because the later internally makes use of `split_terminator` instead and ignores the last line break, meaning `"A\n".lines()` would return `["A"]` while `"A\n".split('\n')` returns `["A", ""]`
