### PR TITLE
fix(rome_js_analyze): improve trivia handling in useSingleVarDeclarator

### LINKED ISSUE #2945: 🐛 Misaligned and wrong code fix for js/useSingleVarDeclarator
### Environment information

[Playground](https://play.rome.tools/?code=var+x%2C+y%0A%0Avar+x+%3D+1%2C%0A++++y+%3D+2&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=true&jsx=true#dgBhAHIAIAB4ACwAIAB5AAoACgB2AGEAcgAgAHgAIAA9ACAAMQAsAAoAIAAgACAAIAB5ACAAPQAgADIA)

### What happened?

Wrong code fix:

`var x, y`

```
warning[[js/useSingleVarDeclarator](https://rome.tools/docs/lint/rules/useSingleVarDeclarator/)]: Declare variables separately
  ┌─ main.js:1:1
  │
1 │ var x, y
  │ --------

Safe fix: Break out into multiple declarations
    | @@ -1,4 +1,4 @@
0   | - var x, y
  0 | + var xvar y.        <----------- no new line
1 1 |   
2 2 |   var x = 1,
3 3 |       y = 2
```

----

Misalignment:
```
var x = 1,
    y = 2
```

```
warning[[js/useSingleVarDeclarator](https://rome.tools/docs/lint/rules/useSingleVarDeclarator/)]: Declare variables separately
  ┌─ main.js:3:1
  │  
3 │ ┌ var x = 1,
4 │ │     y = 2
  │ └─────────'

Safe fix: Break out into multiple declarations
    | @@ -1,4 +1,5 @@
0 0 |   var x, y
1 1 |   
2   | - var x = 1,
  2 | + var x = 1
  3 | + var                  <---------- extra newline

3 4 |       y = 2
```

### Expected result

Correct code fix

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

This PR fixes #2945 by improving how trivia is handled as tokens are moved in the syntax tree mutation. Since that rule isn't really safe to apply I've downgraded its applicability to `MaybeIncorrect`, and modified the CLI tests that were relying on this

I also fixed the issue of separated lists created with the node factory API having an empty slot at the end of the list if the trailing separator was `None` by having the factory function take two iterators (one for the list elements and one for the separators) instead of a single iterator of pairs of list element + an optional separator token. The content of the two iterators are interleaved while building the list, and the separator iterator can simply be one item shorter than the elements iterator in order to omit the last separator without creating an empty slot

## Test Plan

I've added the problematic cases from #2945 to the tests for the `useSingleVarDeclarator` rule, the code actions being emitted for these are now correct

### CODE REVIEW

File: crates/rome_js_analyze/src/analyzers/js/use_single_var_declarator.rs [hunk 1]
```diff
@@ -78,54 +79,150 @@ impl Rule for UseSingleVarDeclarator {
...
-
-                // Clone the entire leading trivia for the first statement, but
-                // trim it to the first newline for the following lines
-                let kind = if is_first {
-                    is_first = false;
-                    kind.clone()
+        // Extract the indentation part from the leading trivia of the kind
+        // token, defined as all whitespace and newline trivia pieces starting
+        // from the token going backwards up to the first newline (included).
+        // If the leading trivia for the token is empty a single newline trivia
```
Comment (ematipico) [inline crates/rome_js_analyze/src/analyzers/js/use_single_var_declarator.rs:99]:
```suggestion
        // If the leading trivia for the token is empty, a single newline trivia
```

File: crates/rome_js_analyze/src/analyzers/js/use_single_var_declarator.rs [hunk 2]
```diff
@@ -78,54 +79,150 @@ impl Rule for UseSingleVarDeclarator {
...
+            leading_trivia
+        } else {
+            vec![(TriviaPieceKind::Newline, String::from("\n"))]
+        };
 
-                if let Some(semicolon_token) = semicolon_token {
-                    builder = builder.with_semicolon_token(semicolon_token.clone());
-                }
+        let last_semicolon_token = semicolon_token.as_ref();
+        let remaining_semicolor_token = semicolon_token.clone().map(|_| make::token(T![;]));
```
Comment (ematipico) [inline crates/rome_js_analyze/src/analyzers/js/use_single_var_declarator.rs:128]: `remaining_semicolor_token` => `remaining_semicolon_token` small typo

**Review by ematipico — APPROVED** [review]
This is surely a lot of logic for handling some trivias, and I am sure that we will face some complications moving forward. We should come up with a standard solution at some point
