### PR TITLE
fix(rslint_parser): Remap `of` keyword in `for` of loops

### LINKED ISSUE #1862: 🐛 Parser: not parsing `OF_KW` keyword
### Environment information

```bash
main branch
```

### What happened?

Our grammar supports the `of` [keyword](https://github.com/rome/tools/blob/main/xtask/js.ungram#L162), but our [parser](https://github.com/rome/tools/blob/main/crates/rslint_parser/src/syntax/stmt.rs#L925) is not updated.

Input
```
for (a of b) {}
```

Output
```
    root: 0: JS_SCRIPT@0..16
      0: (empty)
      1: LIST@0..0
      2: LIST@0..15
        0: FOR_OF_STMT@0..15
          0: FOR_KW@0..4 "for" [] [Whitespace(" ")]
          1: L_PAREN@4..5 "(" [] []
          2: JS_IDENTIFIER_ASSIGNMENT@5..7
            0: IDENT@5..7 "a" [] [Whitespace(" ")]
          3: IDENT@7..10 "of" [] [Whitespace(" ")]  <------------- should be OF_KW
          4: JS_IDENTIFIER_EXPRESSION@10..11
            0: JS_REFERENCE_IDENTIFIER@10..11
              0: IDENT@10..11 "b" [] []
          5: R_PAREN@11..13 ")" [] [Whitespace(" ")]
          6: JS_BLOCK_STATEMENT@13..15
            0: L_CURLY@13..14 "{" [] []
            1: LIST@14..14
            2: R_CURLY@14..15 "}" [] []
      3: EOF@15..16 "" [Whitespace("\n")] []
```

### Expected result

`OF_KW` 😄 

### Configuration file of your project

_No response_

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by MichaReiser**
Remap the `of` identifier to the `of` keyword if used inside an `for(.. of ..)` loop (and it isn't a variable name).

Fixes #1862

## Test Plan

Added a new test case verifying that the `of` keyword gets remapped correctly

### CODE REVIEW

File: crates/rslint_parser/src/syntax/stmt.rs [hunk 1]
```diff
@@ -981,7 +985,11 @@ fn for_head(p: &mut Parser) -> SyntaxKind {
 			// left is a union, no need for wrapping
 			init_or_left.abandon(p);
 			let is_in = p.at(T![in]);
-			p.bump_any();
+			if is_in {
+				p.bump_any();
+			} else {
+				p.bump_remap(T![of]);
```
Comment (ematipico) [inline crates/rslint_parser/src/syntax/stmt.rs:991]: What if `of` is actually missing or we have another keyword? Should we add an error test case?

Comment (MichaReiser) [reply crates/rslint_parser/src/syntax/stmt.rs:991]: Line 964 guarantees that this is either a for in or for of statement. The code is a bit hard to read and I plan to clean up the nesting when re-visiting the error handling.

**Review by ematipico — APPROVED** [review]
