### PR TITLE
fix(rome_js_parser): Adding syntax error for new A?.b()

### LINKED ISSUE #3115: 🐛 Missing syntax error for new A?.b()
### Environment information

```bash
Macos
```

### What happened?

Copy from Typescript repository: 
## Related issues:
https://github.com/microsoft/TypeScript/issues/48653
## Related pull request: 
https://github.com/microsoft/TypeScript/pull/48656

### Expected result

Behave like typescript did.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Adding syntax error for `new A?.b()`
2. Fixes #3115 

## Test Plan
1. Ci should pass
3. Checking the newly added snapshot

### CODE REVIEW

File: crates/rome_js_parser/src/syntax/expr.rs [hunk 1]
```diff
@@ -757,8 +760,16 @@ fn parse_new_expr(p: &mut Parser, context: ExpressionContext) -> ParsedSyntax {
...
     };
 
+    // test_err ts invalid_optional_chain_from_new_expressions
+    // new Test<string>?.test();
+    // new Test?.test();
     if p.at(T!['(']) {
         parse_call_arguments(p).unwrap();
+    } else if p.at(T![?.]) && is_identifier_expression {
+        let error = p
+            .err_builder("Invalid optional chain from new expression.")
```
Comment (IWANABETHATGUY) [inline crates/rome_js_parser/src/syntax/expr.rs:770]: Do we need to add detailed error descriptions like `Typescript`?That would introduce extra overhead,  I think `Invalid optional chain from new expression.` would be enough.

**Comment by MichaReiser** [comment]
This seems to be a new error introduced with TypeScript 4.8. 

Please add a few more complicated tests where the optional chain isn't the first member

```
new A.b?.c()
new (A.b)?.c()
new (A.b?.()).c()
new A.b?.()()

```

File: crates/rome_js_parser/test_data/inline/err/invalid_optional_chain_from_new_expressions.rast [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+            semicolon_token: missing (optional),
+        },
+        JsUnknownStatement {
+            items: [
+                QUESTIONDOT@16..18 "?." [] [],
+                IDENT@18..22 "test" [] [],
+                L_PAREN@22..23 "(" [] [],
+                R_PAREN@23..24 ")" [] [],
+            ],
+        },
```
Comment (MichaReiser) [inline crates/rome_js_parser/test_data/inline/err/invalid_optional_chain_from_new_expressions.rast:37]: The error recovery here isn't ideal. The parser knows that this is an optional chain and should continue to parse it out as such.

Comment (IWANABETHATGUY) [reply crates/rome_js_parser/test_data/inline/err/invalid_optional_chain_from_new_expressions.rast:37]: This error came from previous 

> This seems to be a new error introduced with TypeScript 4.8.
> 
> Please add a few more complicated tests where the optional chain isn't the first member
> 
> ```
> new A.b?.c()
> new (A.b)?.c()
> new (A.b?.()).c()
> new A.b?.()()
> ```
> 
> I'm not sure that it will be feasible to catch all those inside of the parser or if it would be better to implement them as a rule.

Typescript behavior https://www.typescriptlang.org/play?ts=4.8.0-beta#code/HYUw7gBAggdARgfhgYwBQEoBQpKtndJNLHCPeJDdFDbcaCmDWoA

**Comment by IWANABETHATGUY** [comment]
> 

Typescript behavior https://www.typescriptlang.org/play?ts=4.8.0-beta#code/HYUw7gBAggdARgfhgYwBQEoBQpKtndJNLHCPeJDdFDbcaCmDWoA

**Comment by IWANABETHATGUY** [comment]
The testing has been updated.

**Comment by IWANABETHATGUY** [comment]
!bench_parser

File: crates/rome_js_parser/test_data/inline/err/invalid_optional_chain_from_new_expressions.rast (hunk 2 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_parser/test_data/inline/err/invalid_optional_chain_from_new_expressions.rast:37]: This should be another bug of our parser. https://play.rome.tools/?code=new+Test%3Cstring%3E%28%29%3B&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=false&jsx=false#bgBlAHcAIABUAGUAcwB0ADwAcwB0AHIAaQBuAGcAPgAoACkAOwA=, 

**Typescript**
https://www.typescriptlang.org/play?ts=4.8.0-beta&ssl=2&ssc=20&pln=1&pc=1#code/MYGwhgzhAEAqCmEAuAeWA+aBvAvgKADt4B3ORVZAJwEsCBzdACgEoBuIA

I would like to open another pull request to resolve it, I prefer one pr resolve one issue, what do you think?

Comment (IWANABETHATGUY) [reply crates/rome_js_parser/test_data/inline/err/invalid_optional_chain_from_new_expressions.rast]: Done

File: crates/rome_js_parser/src/syntax/typescript/types.rs [hunk 3]
```diff
@@ -1246,7 +1246,7 @@ pub(crate) fn parse_ts_type_arguments_in_expression(p: &mut Parser) -> ParsedSyn
         p.re_lex(ReLexContext::TypeArgumentLessThan);
         let arguments = parse_ts_type_arguments_impl(p, false);
 
-        if p.last() == Some(T![>]) && matches!(p.cur(), T!['('] | BACKTICK) {
+        if p.last() == Some(T![>]) && matches!(p.cur(), T!['('] | BACKTICK | T![?.]) {
```
Comment (IWANABETHATGUY) [inline crates/rome_js_parser/src/syntax/typescript/types.rs:1249]: https://www.typescriptlang.org/play?ts=4.8.0-beta#code/FAEwpgxgNghgTmABAMwK4DsIBcCWB7dRLMAZywB4AVAPgAoBKALkRnQE8BuD4YYs8snBzoA5tQD8AOj5YOQA,  `parse_ts_type_arguments_in_expression` follow a `?.` token is valid in **typescript**

Comment (MichaReiser) [reply crates/rome_js_parser/src/syntax/typescript/types.rs:1249]: Would you mind adding a new test case showing when this is valid?

Comment (MichaReiser) [reply crates/rome_js_parser/src/syntax/typescript/types.rs:1249]: This is related to instantiation expressions that our parser currently doesn't support. I recommend tackling this in a separate PR as it is more involved:

https://github.com/microsoft/TypeScript/commit/e6808c429079d132b906102e0a4194c2f346ac80

**Comment by ematipico** [comment]
Adding `0.10.0` milestone to only signal to not merge this PR before `0.9.0` release

**Comment by IWANABETHATGUY** [comment]
@MichaReiser, Since the  main logic of `InstantiationExpression` have been finished, we could push forward this pull request,

**Comment by IWANABETHATGUY** [comment]
You could refer to this patch pr of https://github.com/microsoft/TypeScript/pull/48656/files, pretty much just porting.

**Comment by IWANABETHATGUY** [comment]
The rest of two patch pr of instantiationExpression only modified https://github.com/microsoft/TypeScript/pull/48659/files#diff-12a6724be007eb1a19d80018c7a63bbc73525ca793a9b3e5da49a4e86bbf457cL5732-L5765 `canFollowTypeArgumentsInExpression`, we could skip now.

**Comment by IWANABETHATGUY** [comment]
Why I want to push forward because this pr has been marked as stale, maybe closed a few days later.

File: crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts [hunk 4]
```diff
@@ -147,6 +147,6 @@ if ((this ?? {}).#bar) { foo.bar; }
 
 (undefined && this ?? {}).#bar;
 (((typeof this) as string) || {}).#bar;
-(new foo || {}).bar;
+// (new foo || {}).bar;
```
Comment (IWANABETHATGUY) [inline crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts:150]: Why I disabled this test case , please refer to https://github.com/rome/tools/issues/3257

Comment (IWANABETHATGUY) [reply crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts:150]: If I don't do this, the CI will crash.  https://github.com/rome/tools/actions/runs/3090461304/jobs/4999289555

**Comment by IWANABETHATGUY** [comment]
!bench_parser

File: crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts (hunk 4 above)
Comment (ematipico) [reply crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts:150]: You could add `// disabled because of https://github.com/rome/tools/issues/3257` to the comment, so we know the reason :)

File: crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts.snap [hunk 5]
```diff
@@ -1,5 +1,6 @@
 ---
 source: crates/rome_js_analyze/tests/spec_tests.rs
+assertion_line: 98
```
Comment (ematipico) [inline crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts.snap:3]: This assertion line was added because you have installed an old version of `insta` (via `cargo install insta`). I know it because I had an old version installed too. I think if you update it and update the snapshots again, it should add the assertion line anymore

**Review by ematipico — APPROVED** [review]

File: crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts (hunk 4 above)
Comment (MichaReiser) [inline crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts:150]: Can you create an issue (if you haven't already) and link to the issue in the comment to make it clear why it is commented out.

File: crates/rome_js_parser/src/syntax/expr.rs [hunk 6]
```diff
@@ -777,6 +777,20 @@ fn parse_new_expr(p: &mut Parser, context: ExpressionContext) -> ParsedSyntax {
...
+
+        p.error(error);
+    }
+    // test_err ts invalid_optional_chain_from_new_expressions
+    // new Test<string>?.test();
+    // new Test?.test();
+    // new A.b?.c()
+    // new (A.b)?.c()
+    // new (A.b?.()).c()
+    // new A.b?.()()
```
Comment (MichaReiser) [inline crates/rome_js_parser/src/syntax/expr.rs:793]: Should these tests be moved to line 781 as they are testing the assertion there?

File: crates/rome_js_parser/src/syntax/expr.rs [hunk 7]
```diff
@@ -777,6 +777,20 @@ fn parse_new_expr(p: &mut Parser, context: ExpressionContext) -> ParsedSyntax {
     // class Test<A, B, C> {}
     // new Test<A, B, C>();
 
+    if p.at(T![?.]) {
+        let error = p
+            .err_builder("Invalid optional chain from new expression.")
```
Comment (MichaReiser) [inline crates/rome_js_parser/src/syntax/expr.rs:782]: Can we add a suggestion similar to Typescript's

```
Invalid optional chain from new expression. Did you mean to call 'Test()'?
```

**Review by MichaReiser — APPROVED** [review]

File: crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts.snap (hunk 5 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts.snap]: Done

File: crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts (hunk 4 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts]: Done

File: crates/rome_js_parser/src/syntax/expr.rs (hunk 6 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_parser/src/syntax/expr.rs:786]: Done

File: crates/rome_js_parser/src/syntax/expr.rs (hunk 7 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_parser/src/syntax/expr.rs]: Done

Comment (IWANABETHATGUY) [reply crates/rome_js_parser/src/syntax/expr.rs]: https://github.com/rome/tools/pull/3118#discussion_r976611236 See

File: crates/rome_js_parser/src/syntax/expr.rs (hunk 6 above)
Comment (MichaReiser) [reply crates/rome_js_parser/src/syntax/expr.rs:796]: The latest version shows the comments below the check. Haven't you pushed the most recent changes yet?

Comment (IWANABETHATGUY) [reply crates/rome_js_parser/src/syntax/expr.rs:796]: Yeah, I should update the test again.

Comment (IWANABETHATGUY) [reply crates/rome_js_parser/src/syntax/expr.rs]: Done
