### PR TITLE
Fix(rome_js_formatter):🐛 fix parenthesis expression bad case

### LINKED ISSUE #2558: Should remove parenthesis, when `member` of ComputedMemberExpression is a `parenthesisExpression`, and `expression` of `parenthesisExpression` is `StringLiteralExpression`
## Input
```js
a[("test")];
```

## Prettier
```js
a["test"];
```
## Rome
```js
a[("test")];
```
https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#YQBbACgAIgB0AGUAcwB0ACIAKQBdADsA
## Expected
match prettier

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
Fix #2558 

## Test Plan
fix the bad case 
```js
a[("test")]
```

### CODE REVIEW

**Comment by MichaReiser** [comment]
I believe this fix is too specific to member expressions. What about computed member assignments? Or any other place where expressions can appear. 

This is prettier's rule for formatting string literal expressions

https://github.com/prettier/prettier/blob/6d02cd9650be29d1b11ab6ff1442eac4f5415c06/src/language-js/needs-parens.js#L507-L528

The way I understand this is that:

* It parenthesis all `StringLiteralExpressions` that are direct children of an `ExpressionStatement`
* Removes parenthesis for all other `StringLiteralExpressions`

This should simplify the logic a bit.

**Comment by IWANABETHATGUY** [comment]
!bench_formatter

File: crates/rome_js_formatter/src/js/expressions/parenthesized_expression.rs [hunk 1]
```diff
@@ -102,10 +102,23 @@ fn parenthesis_can_be_omitted(node: &JsParenthesizedExpression) -> SyntaxResult<
...
+    // and node_precedence should be `Low` due to expression is StringLiteralExpression.
+    // the parenthesis should be omitted.
+    if parent_precedence > node_precedence
+        && !matches!(
+            expression,
+            JsAnyExpression::JsAnyLiteralExpression(
+                JsAnyLiteralExpression::JsStringLiteralExpression(_)
+            )
+        )
+    {
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/js/expressions/parenthesized_expression.rs:119]: The easiest is probably to handle `StringLiteralExpressions` before this line because the precedence isn't relevant for string literals, so there's no point in computing the precedence first.

**Comment by IWANABETHATGUY** [comment]
!bench_formatter

**Review by MichaReiser — APPROVED** [review]
