### PR TITLE
fix(rome_js_analyze): false positives for `noUselessFragments` #3668

### LINKED ISSUE #3668: 🐛 `noUselessFragments` is inconsistent/buggy
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 unset

Rome Configuration:
  Status:               loaded
  Formatter disabled:   true
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   windows

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       6
  Client Name:          Visual Studio Code
  Client Version:       1.73.1
```

### What happened?

# Issue 1
```tsx
function Component1() {
  const str = 'str';
  return <>{str}</>;
}

function Component2() {
  const str = 'str';
  return (<>{str}</>);
}
```

The `noUselessFragments` rule finds an issue in `Component2`, but not in `Component1`, the only difference is the parentheses.

# Issue 2

```tsx
const obj = {
  element: <>test</>
};
```

if I apply the rule suggestion, I end up with this:

```tsx
const obj = {
  "test"
};
```

which is not valid JS.

```
  ! Avoid using unnecessary Fragment.

    176 │ const obj = {
  > 177 │   element: <>test</>
        │            ^^^^^^^^^
    178 │ };
    179 │ 

  i Suggested fix: Remove the Fragment

    175 175 │ 
    176 176 │   const obj = {
    177     │ - ··element:·<>test</>
        177 │ + ··"test"
    178 178 │   };
    179 179 │ 
```

### Expected result

No bugs!

FWIW because of a [TypeScript limitation](https://github.com/microsoft/TypeScript/issues/21699), components cannot return a string for example, otherwise it'll lead to type issues, so some fragments must be preserved in `.tsx` files.

In the second example, I'm not convinced it's safe to remove the fragment there anyway, we don't know where `obj.element` will be used.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Fixes #3668 

## Test Plan

Added two new test cases.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Would you mind giving this PR a more descriptive title. It's hard to guess what it is about from looking at the PR list or git log

File: crates/rome_js_analyze/src/semantic_analyzers/correctness/no_useless_fragments.rs [hunk 1]
```diff
@@ -108,31 +106,42 @@ impl Rule for NoUselessFragments {
         let model = ctx.model();
         match node {
             NoUselessFragmentsQuery::JsxFragment(fragment) => {
-                let matches_allowed_parents = node
+                let parents_where_fragments_must_be_preserved = node
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/semantic_analyzers/correctness/no_useless_fragments.rs:109]: Would it be safer to instead allow list the parents where the fragment must not be preserved? That way adding new AST node types won't break the rule.

Comment (ematipico) [reply crates/rome_js_analyze/src/semantic_analyzers/correctness/no_useless_fragments.rs:109]: I think it wouldn't. I personally see it way harder to maintain

File: crates/rome_js_analyze/src/semantic_analyzers/correctness/no_useless_fragments.rs [hunk 2]
```diff
@@ -108,31 +106,42 @@ impl Rule for NoUselessFragments {
...
-                        Ok(parent) => {
-                            let parent_kind = parent.syntax().parent().kind();
-                            matches!(
-                                parent_kind,
-                                Some(
+                        Ok(parent) => parent
+                            .syntax()
+                            .parent()
+                            .and_then(|parent| {
+                                if let Some(parenthesized_expression) =
```
Comment (leops) [inline crates/rome_js_analyze/src/semantic_analyzers/correctness/no_useless_fragments.rs:117]: This would need to use an equivalent of `omit_parentheses` iterating through the ancestor nodes, or it's only going to catch the first parenthesized expression it encounters and fail on a case like this: `{ key: (((<>content</>))) }`

Comment (ematipico) [reply crates/rome_js_analyze/src/semantic_analyzers/correctness/no_useless_fragments.rs:117]: Yes, I am aware of it and I intentionally left it out. I consider it an edge case that we can tackle if we really know if could cause issue.

**Review by leops — APPROVED** [review]
