### PR TITLE
fix(rome_cli): improve the main help text

### LINKED ISSUE #3415: 🐛 Undocummented `start` and `stop` commands
### Environment information

main (3a6e4346ee26a5a5d2f777ce62995cb900e0ce66)

### What happened?

1. Run `rome --help`
2. Observe that the `start` and `stop` commands aren't documented

```bash
❯ cargo run --bin rome -- --help
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/rome --help`
Rome CLI v0.0.0

COMMANDS:
    - check
    - ci
    - format
    - init
    - help

OPTIONS:
    --no-colors      Disable the formatting of markup (print everything as plain text)
    --use-server     Connect to a running instance of the Rome daemon server

```

### Expected result

`start` and `stop` should be mentioned by `--help`.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

Fixes #3415

This adds the `start` and `stop` commands to the list of commands documented in the "main" help text printed by `rome --help`. I also took the opportunity to add a short summary for the commands in the list to make it easier to see what each command is doing at a glance without having to print the full help text for each command.

## Test Plan

N/A

### CODE REVIEW

File: crates/rome_cli/src/commands/help.rs [hunk 1]
```diff
@@ -11,11 +11,13 @@ const MAIN: Markup = markup! {
 "Rome CLI v"{VERSION}"
 
 "<Emphasis>"COMMANDS:"</Emphasis>"
-    - "<Emphasis>"check"</Emphasis>"
-    - "<Emphasis>"ci"</Emphasis>"
-    - "<Emphasis>"format"</Emphasis>"
-    - "<Emphasis>"init"</Emphasis>"
-    - "<Emphasis>"help"</Emphasis>"
+    - "<Emphasis>"check"</Emphasis>"        Run the linter on a set of files
+    - "<Emphasis>"ci"</Emphasis>"           Run the linter and formatter check on a set of files
```
Comment (MichaReiser) [inline crates/rome_cli/src/commands/help.rs:15]: Nit: `check the formatting` instead of `formatter check` 

Mainly because it isn't described anywhere what `the formatter check` is.

**Review by MichaReiser — APPROVED** [review]

**Review by ematipico — APPROVED** [review]
