### PR TITLE
fix(rome_js_formatter): comments in closing JSX elements

### LINKED ISSUE #4243: 🐛 JsClosingElement erroneous formatting with comments
### Environment information

```block
Rome v11.0.0-nightly.97e48b4
```

### What happened?

The following code:

```ts
<a></ /* comment */
a>;
```

is formatted to a syntactically invalid code:

```ts
<a><//* comment */
a>;
  ^
  Expected `<` but instead the file ends
```

Note the removed space after `</`.

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

This is a tentative to fix #4243.
This is blocking the update of prettier snapshots #4234.

I copied the code from `closing_fragment.rs` because the formatting is correct for fragments:

```ts
<></ /* block1 */ // test
>;
```

is correctly formatted to:

```ts
<></
	/* block1 */
	// test
>;
```

Unfortunately this has no effect:

```
<a></ /* block1 */ // test
a>;
```

still produces the following error:

```
$ cargo test

---- formatter::jsx_module::specs::jsx::comments_jsx stdout ----
thread 'formatter::jsx_module::specs::jsx::comments_jsx' panicked at 'formatter output had syntax errors where input had none:
comments.jsx:3:1 parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ✖ expected `<` but instead the file ends
  
    1 │ <a><//* block1 */ // test
    2 │ a>;
  > 3 │ 
      │ 
  
  ℹ the file ends here
  
    1 │ <a><//* block1 */ // test
    2 │ a>;
  > 3 │ 
      │ 
```

## Test Plan

Test included

## Documentation

No change

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

**Comment by ematipico** [comment]
cc @MichaReiser  that worked on source maps and comments

**Comment by MichaReiser** [comment]
I recommend reading prettier's source code to understand their formatting (and how it may have changed)

**Comment by Conaclos** [comment]
> I recommend reading prettier's source code to understand their formatting (and how it may have changed)

I already have an idea for addressing the issue.

My current problem is with the Rome code base. I cannot understand why my piece of code fails.
I certainly have some misunderstanding about comment handling in the formatter.

In the following code, `/* comment */` is a trailing comment of `/`.

```ts
<a></ /* comment */a>
```

I think so that it was also a **dangling comment** of the entire _JsxClosingElement_ `</ /* comment */a>`.
However, this seems not be the case?
Is there a way to collect all comments inside the node?

**Comment by MichaReiser** [comment]
> In the following code, /* comment */ is a trailing comment of /.

`/* comment */` is a leading comment of the `a` node in this example because it is before the start of the `a` node. The [comments module](https://rustdocs.rome.tools/rome_formatter/comments/index.html) explains the comments handling in detail. 

JavaScript also has an [extensive list](https://github.com/rome/tools/blob/36103b2c11ad409d21ca7fb2bb117c0710248c95/crates/rome_js_formatter/src/comments.rs#L159-L205) of custom-rules for placing comments (same as prettier). 

The way I like to approach issues with comments is to log the comments inside the test

```rust
let syntax = SourceType::jsx();
let tree = parse("<a></ /* block1 */ // test\na>;", syntax);

let formatted = format_node(JsFormatOptions::new(syntax), &tree.syntax()).unwrap();

dbg!(&formatted.context().comments());
```

That helps me understand if the comments are associated with the correct nodes. You may want to compare the output with Prettier using their playground. 

image

**Comment by Conaclos** [comment]
@MichaReiser 
Thanks for the tips :)
I will take another look.

> /* comment */ is a leading comment of the a node in this example because it is right before the node a starts.

In the [playground](https://docs.rome.tools/playground/?code=PABhAD4APAAvACAALwAqACAAYwBvAG0AbQBlAG4AdAAgACoALwBhAD4A), `/* comment */` is a trailing trivia of `/`...

**Comment by Conaclos** [comment]
The fix is not ideal. However, this removes one of the issues that block the update of prettier snapshots.

File: crates/rome_js_formatter/src/jsx/tag/closing_element.rs [hunk 1]
```diff
@@ -7,24 +7,37 @@ use rome_js_syntax::{JsxClosingElement, JsxClosingElementFields};
...
         let JsxClosingElementFields {
             l_angle_token,
             slash_token,
             name,
             r_angle_token,
         } = node.as_fields();
 
+        let mut name_has_leading_comment = false;
+        let mut name_has_own_line_leading_comment = false;
+        for leading_comment in f.comments().leading_comments(name.clone()?.syntax()) {
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/jsx/tag/closing_element.rs:20]: Nit: You can avoid cloning by using 

```rust
let name = name?;

....

f.comments().leading_comments(name.syntax())
```

Or you can write

```rust
f.comments().leading_comments(name.as_ref()?.syntax())
```

**Review by MichaReiser — COMMENTED** [review]
How does this approach compare to prettier's handling? What do you consider non-ideal with this solution?

**Comment by Conaclos** [comment]
> How does this approach compare to prettier's handling? What do you consider non-ideal with this solution?

In prettier the following code:

```ts
<a></ /* block1 */ // test
a>;
```

is formatted to:

```ts
<a></
  /* block1 */ // test
  a
>;
```

While the current fix output:

```ts
<a></
/* block1 */ // test
a>;
```

**Comment by Conaclos** [comment]
Follow-up:

I tried to apply `indent` on `format_name`, however, this only indent `a`.

**Comment by Conaclos** [comment]
@MichaReiser I managed to match _prettier_ output :)

It was harder than I thought to understand the formatter logic.

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
Amazing work @Conaclos !!!

> It was harder than I thought to understand the formatter logic.

Yeah dealing with the formatter is not a easy task!
