### PR TITLE
fix(rome_js_analyze): should handle read-only arrays

### LINKED ISSUE #3864: 📎 `useShorthandArrayType` should handle read-only arrays
## Summary

For now, *Rome*'s `useShorthandArrayType` does not handle read-only arrays.
ESLint's rule [array-type](https://typescript-eslint.io/rules/array-type) handles read-only arrays.

## Examples

This code:

```ts
const y: ReadonlyArray<string> = ['a', 'b'];
```

should be turned into:

```ts
const y: readonly string[] = ['a', 'b'];
```

### PR DESCRIPTION
**Pull request by unvalley**
## Summary
Closes  #3864

- ~~add readonly modifier to TsArrayType by editing js.ungram~~
	- ~~This causes lots of file changes.~~

## Test Plan

```
cargo test // on rome_js_analyze
```

### CODE REVIEW

**Review by MichaReiser — CHANGES_REQUESTED** [review]
`readonly` is a type operation and is represented by the `TsTypeOperatorType` node. You can inspect the AST of an array with a readonly operation by opening [this playground](https://docs.rome.tools/playground/?indentStyle=space&trailingComma=none&code=dAB5AHAAZQAgAEEAIAA9ACAAcgBlAGEAZABvAG4AbAB5ACAAWwBzAHQAcgBpAG4AZwBdADsA). 

It's, therefore, not necessary to change the AST to support readonly arrays. Instead, the lint must create a new `TsTypeOperatorType` where the `operation_token` is `readonly` and `ty` is the array type

**Comment by unvalley** [comment]
@MichaReiser Thanks, I've fixed to use `TsTypeOperatorType`. Please take a look.

File: crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs [hunk 1]
```diff
@@ -120,24 +157,43 @@ fn convert_to_array_type(type_arguments: TsTypeArguments) -> Option<AnyTsType> {
...
                 };
                 element_type.map(|element_type| {
-                    AnyTsType::TsArrayType(make::ts_array_type(
+                    let array_type = make::ts_array_type(
                         element_type,
                         make::token(T!['[']),
                         make::token(T![']']),
-                    ))
+                    );
+                    let readonly_token = JsSyntaxToken::new_detached(
```
Comment (leops) [inline crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs:178]: Nit: let's move this inside the `TsArrayKind::Readonly => {}` branch to avoid creating a token if it's not getting used

**Review by leops — APPROVED** [review]

**Review by MichaReiser — APPROVED** [review]

File: crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs (hunk 1 above)
Comment (unvalley) [reply crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs:178]: Thanks, I'll fix.

Comment (unvalley) [reply crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs]: @leops done at c310baa
