### PR TITLE
fix(rome_js_parser): call expression in optional member chain followed by `<`

### LINKED ISSUE #3486: 🐛 Parser: `<` inside a chained optional call expression
### Environment information

[PlayGround](https://play.rome.tools/?code=item+%3D%3E+String%28item%29%3F.indexOf%28filterIdPrefix%29+%3C+0&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=script&enabledNurseryRules=true&typescript=false&jsx=false#aQB0AGUAbQAgAD0APgAgAFMAdAByAGkAbgBnACgAaQB0AGUAbQApAD8ALgBpAG4AZABlAHgATwBmACgAZgBpAGwAdABlAHIASQBkAFAAcgBlAGYAaQB4ACkAIAA8ACAAMAA=)

### What happened?

```javascript
item => String(item)?.indexOf(filterIdPrefix) < 0
```

errored with

```
  ✖ expected an identifier but instead found '<'
```

### Expected result

It should parse

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by MichaReiser**
This PR fixes a false diagnostic for call expressions that are part of an optional chain (static member) that are then followed by a binary `<` expression.

```
String(item)?.b <aBcd;
```

The problem is that the error recovery code for `a.test?.` incorrectly kicked in which should not happen if what followed after the call expression is a valid static member expression in an optional chain.

fixes #3486

### CODE REVIEW

File: crates/rome_js_parser/src/syntax/expr.rs [hunk 1]
```diff
@@ -1720,30 +1720,32 @@ fn parse_call_expression_rest(
...
-            lhs = m.complete(p, JS_STATIC_MEMBER_EXPRESSION);
         } else {
-            // Safety:
-            // * The method initially checks if the parsers at a '<', '(', or '?.' token.
-            // * if the parser is at '?.': It takes the branch right above, ensuring that no token was consumed
-            // * if the parser is at '<': `parse_ts_type_arguments_in_expression` rewinds if what follows aren't  valid type arguments and this is the only way we can reach this branch
-            // * if the parser is at '(': This always parses out as valid arguments.
-            debug_assert_eq!(p.tokens.position(), start_pos);
-            m.abandon(p);
+            break if optional_chain_call {
```
Comment (MichaReiser) [inline crates/rome_js_parser/src/syntax/expr.rs:1724]: The main fix is to test for `optional_chain_call` instead of `in_optional_chain`. The former is only true for `a()?.` but the latter can also be true for `a()?.b` (which has already been handled by the member expression parsing
