### PR TITLE
fix(useOptionalChain): ignore expr ending with a bin expr

### LINKED ISSUE #4216: 📎 `useOptionalChain` ignore expressions ending with a binary expression
### Description

This is a task extracted from #4145.

The idea  is to prevent the following erroneous simplification:

```diff
- foo && foo.bar !== null
+ foo?.bar !== null
```

As a simple rule we could prevent the simplification of any expression that ends with a binary expression:

```js
foo && <binary-expression>
```

Note that we should still handle the following simplification:

```diff
- foo !== null && foo.bar
+ foo?.bar
```

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fixes #4216

## Test Plan

Tests included.

## Documentation

No change

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

File: crates/rome_js_analyze/src/analyzers/complexity/use_optional_chain.rs [hunk 1]
```diff
@@ -299,6 +299,15 @@ impl Rule for UseOptionalChain {
     }
 }
 
+fn simplified_expression(expression: AnyJsExpression) -> SyntaxResult<AnyJsExpression> {
```
Comment (ematipico) [inline crates/rome_js_analyze/src/analyzers/complexity/use_optional_chain.rs:302]: Nit: we should add some documentation to explain what this function does; looking at the name and its implementation, it's not clear to me

**Review by ematipico — APPROVED** [review]
