### PR TITLE
fix(rome_diagnostics): fix unknown rule warning false positive

### LINKED ISSUE #3406: 🐛 Formatter prints lots of `Unknown lint rule_______ in suppression comment`
### Environment information

```bash
macOS 12.6
Rome CLI v0.10.1-next
```

### What happened?

Repro steps:

```
shell
git clone https://github.com/cubing/cubing.js
cd cubing.js
git checkout 4b8891790c651de031d8a35dd7687f59db5e84e2
npm install
npx rome format --write ./script ./src
```

Output (truncated):

```
./src/sites/experiments.cubing.net/cubing.js/speechcubing/index.ts:39:5 suppressions/unknownRule ━━━

  ⚠ Unknown lint rule correctness/useTemplate in suppression comment

    37 │   const latestResult = event.results.item(event.results.length - 1);
    38 │   alternativeListElem.textContent =
  > 39 │     // rome-ignore lint(correctness/useTemplate): Using a template would make this more confusing.
       │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    40 │     "Raw alternatives: " +
    41 │     Array.from(latestResult)


./src/cubing/search/instantiator.ts:17:3 suppressions/unknownRule ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ Unknown lint rule correctness/noAsyncPromiseExecutor in suppression comment

    16 │ export async function instantiateModuleWorker(): Promise<WorkerInsideAPI> {
  > 17 │   // rome-ignore lint(correctness/noAsyncPromiseExecutor): TODO
       │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    18 │   return new Promise<WorkerInsideAPI>(async (resolve, reject) => {
    19 │     const timeoutID = setTimeout(() => {


./src/cubing/alg/parseAlg.ts:140:9 suppressions/unknownRule ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ Unknown lint rule correctness/noUnnecessaryContinue in suppression comment

    138 │           algStartIdx = this.#idx;
    139 │         }
  > 140 │         // rome-ignore lint(correctness/noUnnecessaryContinue): This line allows for more robust refactoring.
        │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    141 │         continue mainLoop;
    142 │       } else if (MOVE_START_REGEX.test(this.#input[this.#idx])) {


./src/cubing/alg/parseAlg.ts:149:9 suppressions/unknownRule ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ Unknown lint rule correctness/noUnnecessaryContinue in suppression comment

    147 │         algEndIdx = this.#idx;
    148 │
  > 149 │         // rome-ignore lint(correctness/noUnnecessaryContinue): This line allows for more robust refactoring.
        │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    150 │         continue mainLoop;
    151 │       } else if (this.tryConsumeNext("(")) {


./src/cubing/alg/parseAlg.ts:179:11 suppressions/unknownRule ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ Unknown lint rule correctness/noUnnecessaryContinue in suppression comment

    177 │           algEndIdx = this.#idx;
    178 │
  > 179 │           // rome-ignore lint(correctness/noUnnecessaryContinue): This line allows for more robust refactoring.
        │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    180 │           continue mainLoop;
    181 │         } else {


./src/cubing/alg/parseAlg.ts:195:11 suppressions/unknownRule ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ Unknown lint rule correctness/noUnnecessaryContinue in suppression comment

    193 │           algEndIdx = this.#idx;
    194 │
  > 195 │           // rome-ignore lint(correctness/noUnnecessaryContinue): This line allows for more robust refactoring.
        │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    196 │           continue mainLoop;
    197 │         }


./src/cubing/alg/parseAlg.ts:231:13 suppressions/unknownRule ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ Unknown lint rule correctness/noUnnecessaryContinue in suppression comment

    229 │             algEndIdx = this.#idx;
    230 │
  > 231 │             // rome-ignore lint(correctness/noUnnecessaryContinue): This line allows for more robust refactoring.
        │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    232 │             continue mainLoop;
    233 │           }
```

### Expected result

No warnings about suppressed errors.

The VSCode extension seems to recognize these `// rome-ignore` comments as valid syntax, I'm not sure why the CLI doesn't.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

Fixes #3406

This PR changes how the "rule registry" concept of the analyzer works by splitting its various use-case into separate types implemented at different location in the codebase through a common `RegistryVisitor` trait. This trait makes it possible to differentiate between the "static registry" containing all the rules for a given language (implemented through the new `visit_registry` function replacing `build_registry`), and various "dynamic registries" that get built on demand throughout the codebase: the analyzer holds both a fast set of all the known rules and a `RuleRegistry` containing only the active rules, the `lintdoc` tools builds a list of the lint rules only, the LSP also needs to build a list of the code action rules, ...

## Test Plan

I've added an additional test for suppression comments to ensure the analyzer does not emit an "unknown rule" diagnostic on a suppression comment for a rule whose category is disabled. The rest of the change should be covered by the existing tests for the corresponding area of the codebase.

### CODE REVIEW

File: crates/rome_analyze/src/registry.rs [hunk 1]
```diff
@@ -34,22 +34,87 @@ impl Phase for () {
...
+pub struct MetadataRegistry {
+    inner: BTreeSet<MetadataKey>,
+}
+
+impl MetadataRegistry {
+    /// Return a unique identifier for a rule group if it's known by this registry
+    pub fn find_group(&self, group: &str) -> Option<GroupKey> {
+        let key = self.inner.get(group)?;
+        let (key, _) = key.inner;
+        Some(GroupKey::new(key))
```
Comment (MichaReiser) [inline crates/rome_analyze/src/registry.rs:68]: Nit: For symmetry: `key.into_group_key()`?

File: crates/rome_analyze/src/registry.rs [hunk 2]
```diff
@@ -62,32 +127,37 @@ struct PhaseRules<L: Language> {
     rule_states: Vec<RuleState<L>>,
 }
 
-impl<L: Language + Default> RuleRegistry<L> {
-    pub fn push_category<C: GroupCategory<Language = L>>(&mut self, filter: &AnalysisFilter) {
-        if filter.match_category::<C>() {
-            C::push_groups(self, filter);
+pub struct RuleRegistryBuilder<'a, L: Language> {
+    pub registry: RuleRegistry<L>,
```
Comment (MichaReiser) [inline crates/rome_analyze/src/registry.rs:131]: Would it be possible to remove the `pub` from `registry` and `filter`. My understanding would be that this is internal state that the builder uses to build the final registry when calling `build`.

File: xtask/lintdoc/src/main.rs [hunk 3]
```diff
@@ -56,20 +59,36 @@ fn main() -> Result<()> {
     // failure instead of just the first one
     let mut errors = Vec::new();
 
-    let filter = AnalysisFilter {
-        categories: RuleCategories::LINT,
-        ..AnalysisFilter::default()
-    };
+    #[derive(Default)]
+    struct RulesVisitor {
```
Comment (MichaReiser) [inline xtask/lintdoc/src/main.rs:63]: Nit: LintRulesVisitor?

File: crates/rome_service/src/file_handlers/javascript.rs [hunk 4]
```diff
@@ -264,14 +293,7 @@ fn code_actions(
...
     if let Some(enabled_rules) = &mut enabled_rules {
-        let actions_filter = AnalysisFilter {
-            categories: RuleCategories::ACTION,
-            ..AnalysisFilter::default()
-        };
-
-        for meta in metadata(&actions_filter) {
-            enabled_rules.push(RuleFilter::Rule(meta.group, meta.rule.name));
-        }
+        visit_registry(&mut ActionsVisitor { enabled_rules });
```
Comment (MichaReiser) [inline crates/rome_service/src/file_handlers/javascript.rs:296]: My understanding is that `visit_registry` performs a "side effect" by adding the rules to the passed visitor. How does this work here where the passed visitor isn't used after the `visit_registry`? What's the necessary side effect?

OK, I get it... it works with enabled rules. I wonder if it would be easier to understand if the two ifs (one initializing `enabled_rules` and the if here) are collapsed and instead it's written like

```rust
let enabled_rules = if let Some(rules) = rules {
    let enabled = rules.as_enabled_rules().into_iter().collect();
    let mut visitor = ActionsVisitor { enabled_rules };
    visit_registry(&mut visitor);
    visitor.enabled_rules
}
```

File: crates/rome_service/src/configuration/mod.rs [hunk 5]
```diff
@@ -326,8 +330,45 @@ where
...
+    let mut visitor = MetadataVisitor {
+        registry: BTreeSet::default(),
+        filter,
+    };
+
+    visit_registry(&mut visitor);
+
     let mut analyzer_rules = AnalyzerRules::default();
-    let mut metadata = metadata(filter);
+    let mut metadata = visitor.registry.into_iter();
```
Comment (MichaReiser) [inline crates/rome_service/src/configuration/mod.rs:371]: Would it be possible to use the "default" meta data visitor here? Or is the filtering being done to avoid initializing options of disabled rules?

Comment (leops) [reply crates/rome_service/src/configuration/mod.rs:371]: I didn't want to disrupt this area of the code to avoid a conflict with #3381 but since that's now merged it should be alright to change this a bit more in depth to make use of the `MetadataRegistry`

**Review by MichaReiser — APPROVED** [review]

**Comment by ematipico** [comment]
This the error we were trying to fix originated via CLI, it would have been great to add a test in the CLI crate

**Comment by leops** [comment]
> Since the error we were trying to fix originated via CLI, it would have been great to add a test in the CLI crate

It's not really a "CLI-exclusive" error, since the root cause is in the analyzer it also happens in the LSP, the only reason it doesn't show up in the editor is that we don't report warnings that are emitted during formatting
