### PR TITLE
fix: keep quotes in the case of keys that are octal literals

### LINKED ISSUE #4284: 🐛 Formatter strips quotes from keys that are octal literals
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Incompatible Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Rome.

Server:
  Version:              <=10.0.0

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              11.0.0
  Name:                 rome_lsp
  CPU Architecture:     aarch64
  OS:                   macos

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       3
  Client Name:          Visual Studio Code
  Client Version:       1.76.0
```

### What happened?

https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&code=YwBvAG4AcwB0ACAAeAAgAD0AIAB7AAoAIAAgADgAOgAgACcAeQBhAHkAJwAsAAoAIAAgACcAMAAxADAAJwA6ACAAJwBvAGgAIABuAG8AJwAsAAoAfQA7AAoAYwBvAG4AcwBvAGwAZQAuAGwAbwBnACgAeABbADgAXQApADsA&typescript=false&jsx=false

This code outputs "yay":

```js
const x = {
  8: 'yay',
  '010': 'oh no',
};
console.log(x[8]);
```

Running it through Rome produces this code

```js
const x = {
  8: 'yay',
  010: 'oh no',
};
console.log(x[8]);
```

Which outputs "oh no".

This is because Rome is stripping quotes from keys which are interpreted as legacy octal literals.

If you are running with `use strict` it won't even parse.

### Expected result

Rome should not alter the behaviour of my program by changing the formatting. Prettier gets this right.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by nissy-dev**
## Summary

Fix #4284

## Test Plan

I updated tests and confirmed the issue was fixed.

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

File: crates/rome_js_formatter/src/utils/string_utils.rs [hunk 1]
```diff
@@ -247,6 +247,11 @@ impl<'token> LiteralStringNormaliser<'token> {
         let mut has_seen_number = false;
         text_to_check.chars().enumerate().all(|(index, c)| {
             if index == 0 && c.is_numeric() {
```
Comment (denbezrukov) [inline crates/rome_js_formatter/src/utils/string_utils.rs:249]: I was wondering if we have to use here `[is_ascii_digit](https://doc.rust-lang.org/std/primitive.char.html#method.is_ascii_digit)` What do you think? 
Because `is_numeric` https://doc.rust-lang.org/std/primitive.char.html#method.is_numeric
```
assert!('৬'.is_numeric());
assert!('¾'.is_numeric());
assert!('①'.is_numeric());
```
I'm not sure if it's valid. 
Could you test please? 🙏

File: crates/rome_js_formatter/tests/specs/js/module/string/properties_quotes.js.snap [hunk 2]
```diff
@@ -103,7 +102,7 @@ let { _$_ff$_morning_not_quotes: test, "_$_ff$_morning_yes_quotes_@": test } =
 
 let { "_$_$_%": test } = value;
 
-let { 0197: test, "3n": test, "3p": test, p9: test } = value;
+let { "0197": test, "3n": test, "3p": test, p9: test } = value;
```
Comment (denbezrukov) [inline crates/rome_js_formatter/tests/specs/js/module/string/properties_quotes.js.snap:105]: It seems that it's regression.

https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&code=YwBvAG4AcwB0ACAAeAAgAD0AIAB7AAoAIAAgADgAOgAgACcAeQBhAHkAJwAsAAoAIAAgACcAMAAxADAAJwA6ACAAJwBvAGgAIABuAG8AJwAsAAoAfQA7AAoAYwBvAG4AcwBvAGwAZQAuAGwAbwBnACgAeABbADgAXQApADsACgAKAGwAZQB0ACAAewAgADAAMQA5ADcAOgAgAHQAZQBzAHQALAAgACIAMwBuACIAOgAgAHQAZQBzAHQALAAgACIAMwBwACIAOgAgAHQAZQBzAHQALAAgAHAAOQA6ACAAdABlAHMAdAAgAH0AIAA9ACAAdgBhAGwAdQBlADsACgA%3D&typescript=false&jsx=false

File: crates/rome_js_formatter/src/utils/string_utils.rs (hunk 1 above)
Comment (ematipico) [reply crates/rome_js_formatter/src/utils/string_utils.rs:249]: @denbezrukov do you have an use case/test case that we can use ?

Comment (denbezrukov) [reply crates/rome_js_formatter/src/utils/string_utils.rs:249]: Sure,
https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&code=YwBvAG4AcwB0ACAAeAAgAD0AIAB7AAoAIAAgADgAOgAgACcAeQBhAHkAJwAsAAoAIAAgACcAvgC%2BAL4AvgAnADoAIAAnAG8AaAAgAG4AbwAnACwACgAgACAAJwBgJCcAOgAgACcAMQAyADMAJwAKAH0AOwAKAGMAbwBuAHMAbwBsAGUALgBsAG8AZwAoAHgAWwA4AF0AKQA7AA%3D%3D&typescript=false&jsx=false

Comment (nissy-dev) [reply crates/rome_js_formatter/src/utils/string_utils.rs]: I use `is_ascii_digit` and update test 👍

**Review by ematipico — APPROVED** [review]

File: crates/rome_js_formatter/tests/specs/js/module/string/properties_quotes.js.snap [hunk 3]
```diff
@@ -103,7 +107,12 @@ let { _$_ff$_morning_not_quotes: test, "_$_ff$_morning_yes_quotes_@": test } =
...
+
+const x = {
+	¾¾¾¾: "test1",
+	①: "test2",
```
Comment (denbezrukov) [inline crates/rome_js_formatter/tests/specs/js/module/string/properties_quotes.js.snap:114]: I guess that correct is 
```
const x = {
	"¾¾¾¾": "test1",
	"①": "test2",
};
```

Comment (nissy-dev) [reply crates/rome_js_formatter/tests/specs/js/module/string/properties_quotes.js.snap]: I tried to fix in [10b568f](https://github.com/rome/tools/pull/4309/commits/10b568f112cacd842aa7a8acb3fc4e4c9d52440f)
