### PR TITLE
fix(rome_js_analyze): fix a false positive for `noDuplicateCase`

### LINKED ISSUE #4706: 🐛 `noDuplicateCase` false positive on quotes
### Environment information

```block
CLI:
  Version:                      12.1.3-nightly.f65b0d9
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.16.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/3.6.1"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Workspace:
  Open Documents:               0

Discovering running Rome servers...

Incompatible Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Rome.

Server:
  Version:                      12.1.3
```

### What happened?

When using a switch statement with cases for both single quotes (`'`) and double quotes (`"`), a `lint/suspicious/noDuplicateCase` is being thrown even though it is a valid scenario. 

[Playground](https://docs.rome.tools/playground/?quoteStyle=single&code=ZgB1AG4AYwB0AGkAbwBuACAAcwBvAG0AZQBFAHMAYwBhAHAAZQBGAHUAbgBjAHQAaQBvAG4AKAApACAAewAKACAAIABzAHcAaQB0AGMAaAAgACgAYwApACAAewAKACAAIAAgACAAYwBhAHMAZQAgACIAJwAiADoACgAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgACcAJgBhAHAAbwBzADsAJwA7AAoAIAAgACAAIABjAGEAcwBlACAAJwAiACcAOgAKACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJwAmAHEAdQBvAHQAOwAnADsACgAgACAAfQAKAH0A)

### Expected result

It should not throw an error

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #4706

## Test Plan

Regression test included.

### CODE REVIEW

File: crates/rome_js_syntax/src/lib.rs [hunk 1]
```diff
@@ -272,3 +272,30 @@ impl OperatorPrecedence {
...
+///
+/// let a = JsSyntaxToken::new_detached(JsSyntaxKind::LET_KW, "let", [], []);
+/// let b = JsSyntaxToken::new_detached(JsSyntaxKind::LET_KW, "let", [], []);
+/// assert_eq!(inner_text(&a), inner_text(&b));
+///
+/// let a = JsSyntaxToken::new_detached(JsSyntaxKind::LET_KW, "let", [], []);
+/// let b = JsSyntaxToken::new_detached(JsSyntaxKind::CONST_KW, "const", [], []);
+/// assert!(inner_text(&a) != inner_text(&b));
+/// ```
+pub fn inner_text(token: &JsSyntaxToken) -> &str {
```
Comment (ematipico) [inline crates/rome_js_syntax/src/lib.rs:295]: Two questions:
- we have some `inner_text` functions already, weren't they sufficient?
- why did you implement it as a function not inside as `impl` for syntax tokens?

Comment (Conaclos) [reply crates/rome_js_syntax/src/lib.rs:295]: This is JS-spêcific, while `SyntaxToken` is more general. It is not possible to write an `impl` on a type-alias such as `JsSyntaxToken`?

Which `inner_text` do you refer to?
