### PR TITLE
Fix(rome_js_formatter): 🎸 Switch-case block body placement 

### LINKED ISSUE #2407: Switch-case block body placement
Rome's formatter places a switch case's block body on a new line and indents it whereas Prettier formats the block start on the same line as the case start. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#CgBzAHcAaQB0AGMAaAAgACgAIgB0AGUAcwB0ACIAKQAgAHsACgAgACAAYwBhAHMAZQAgACIAdABlAHMAdAAiADoAIAB7AH0ACgB9AAoA)

## Input

```ts
switch ("test") {
  case "test": {}
}
```

## Prettier
```ts
switch ("test") {
	case "test": {
	}
}
```

## Rome 
```ts
switch ("test") {
	case "test":
		{}
}
```

## Expected

Formatting to match Prettier's formatting.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
fix #2407 

## Test Plan
The snapshot testing result should match prettier
Except for some controversial ones I'll list below

### CODE REVIEW

File: crates/rome_js_formatter/tests/specs/prettier/js/arrays/issue-10159.js.snap [hunk 1]
```diff
@@ -14,24 +15,26 @@ expression: issue-10159.js
 # Output
 ```js
 {
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/prettier/js/arrays/issue-10159.js.snap:17]: Those are some changes since I modified the https://github.com/IWANABETHATGUY/tools/blob/c2a467e1a01bb0fc01283f2eb43b2c52e48f7dfb/crates/rome_js_formatter/src/js/statements/block_statement.rs#L37.
The block statement behavior should match to prettier, 
https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#ewBmAG8AcgAgACgAYwBvAG4AcwB0ACAAcwByAGMAUABhAHQAaAAgAG8AZgAgAFsAcwByAGMALAAgAGAAJAB7AHMAcgBjAH0ALgBqAHMAYAAsACAAYAAkAHsAcwByAGMAfQAvAGkAbgBkAGUAeABgACwAIABgACQAewBzAHIAYwB9AC8AaQBuAGQAZQB4AC4AagBzAGAAXQApACAAewB9AH0ACgB7AGYAbwByACAAKABjAG8AbgBzAHQAIABzAHIAYwBQAGEAdABoACAAbwBmACAAWwAxADIAMwAsACAAMQAyADMAXwAxADIAMwBfADEAMgAzACwAIAAxADIAMwBfADEAMgAzAF8AMQAyADMAXwAxACwAIAAxADMAXwAxADIAMwBfADMAMQAyADMAXwAzADEAXwA0ADMAXQApACAAewB9AH0ACgB7AGYAbwByACAAKABjAG8AbgBzAHQAIABzAHIAYwBQAGEAdABoACAAbwBmACAAWwAxADIAMwAsACAAMQAyADMAXwAxADIAMwBfADEAMgAzACwAIAAxADIAMwBfADEAMgAzAF8AMQAyADMAXwAxACwAIAAxADMAXwAxADIAMwBfADMAMQAyADMAXwAzADEAXwA0ADMAMgBdACkAIAB7AH0AfQAKAHsAZgBvAHIAIAAoAGMAbwBuAHMAdAAgAHMAcgBjAFAAYQB0AGgAIABvAGYAIABbADEAMgAzACwAIAAxADIAMwBfADEAMgAzAF8AMQAyADMALAAgADEAMgAzAF8AMQAyADMAXwAxADIAMwBfADEALAAgADEAMwBfADEAMgAzAF8AMwAxADIAMwBfADMAMQBfADQAMwAyADEAXQApACAAewB9AH0A

File: crates/rome_js_formatter/tests/specs/prettier/js/babel-plugins/decimal.js.snap [hunk 2]
```diff
@@ -47,13 +46,17 @@ typeof 1m === "decimal128";
 .1m
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/prettier/js/babel-plugins/decimal.js.snap:46]: Those changes are due to changes of https://github.com/IWANABETHATGUY/tools/blob/c2a467e1a01bb0fc01283f2eb43b2c52e48f7dfb/crates/rome_js_formatter/src/js/statements/block_statement.rs#L37, Since those `blockStatement` parent are `JS_MODULE_ITEM_LIST`. According to https://github.com/prettier/prettier/blob/main/src/language-js/print/block.js#L19, should insert a new line after `{`

File: crates/rome_js_formatter/tests/specs/prettier/js/comments/switch.js.snap [hunk 3]
```diff
@@ -77,15 +76,13 @@ switch (foo) {
...
+  } //comment
 
-  case "baz":
-    {
-      doThing();
-    } //comment
+  case "baz": {
+    doThing();
+  } //comment
 }
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/prettier/js/comments/switch.js.snap:86]: Align to prettier behavior

File: crates/rome_js_formatter/tests/specs/prettier/js/module-blocks/module-blocks.js.snap [hunk 4]
```diff
@@ -77,7 +76,8 @@ module;
 }
 
 const m = module;
-{}
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/prettier/js/module-blocks/module-blocks.js.snap:80]: parent is `JS_MODULE_ITEM_LIST`, should insert a new line

File: crates/rome_js_formatter/tests/specs/prettier/js/module-blocks/non-module-blocks.js.snap [hunk 5]
```diff
@@ -14,7 +13,8 @@ const m = module
 # Output
 ```js
 const m = module;
-{}
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/prettier/js/module-blocks/non-module-blocks.js.snap:17]: The same as above

File: crates/rome_js_formatter/tests/specs/prettier/js/optional-catch-binding/optional_catch_binding.js.snap [hunk 6]
```diff
@@ -20,7 +19,10 @@ finally {
 
 # Output
 ```js
-try {} catch {} finally {}
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/prettier/js/optional-catch-binding/optional_catch_binding.js.snap:23]: align to prettier

File: crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap [hunk 7]
```diff
@@ -30,7 +29,8 @@ class Product {
 ```js
 function save(filename = throw new TypeError("Argument required")
 )
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap:31]: parent is `JS_MODULE_ITEM_LIST`, should insert a new line

**Comment by IWANABETHATGUY** [comment]
```bash
test specs::prettier::typescript::webhost::webtsc ... ok

failures:

---- specs::prettier::js::try_::try_ stdout ----
Differences (-input|+output):
                         Line(Hard),
                         SyntaxTokenSlice("/* missing comment */"),
                         Line(Hard),
                     ],
                 ),
-                Group(
-                    List [
-                        SyntaxTokenSlice("{"),
-                        SyntaxTokenSlice("}"),
-                    ],
-                ),
+                SyntaxTokenSlice("{"),
+                Line(Hard),
+                SyntaxTokenSlice("}"),
                 Space,
                 SyntaxTokenSlice("finally"),
                 Space,
                 SyntaxTokenSlice("{"),
                 Line(Hard),

thread 'main' panicked at 'assertion failed: `(left == right)`'
  left: `"try\n/* missing comment */\n{} finally {\n}\n"`
 right: `"try\n/* missing comment */\n{\n} finally {\n}\n"`

Differences (-left|+right):
 try
 /* missing comment */
-{} finally {
+{
+} finally {
 }

', crates/rome_js_formatter/tests/check_reformat.rs:60:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: prettier_tests::check_reformat::check_reformat
             at ./tests/check_reformat.rs:60:9
   3: prettier_tests::test_snapshot
             at ./tests/prettier_tests.rs:95:17
   4: prettier_tests::specs::prettier::js::try_::try_
             at ./tests/prettier_tests.rs:23:1
   5: prettier_tests::specs::prettier::js::try_::try_::{{closure}}
             at ./tests/prettier_tests.rs:23:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    specs::prettier::js::try_::try_
```
@ematipico This is the only test case I failed, but I don't know how to change the test case, 
actually, the new test result should be alright, according to prettier 
https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#dAByAHkACgAvACoAIABtAGkAcwBzAGkAbgBnACAAYwBvAG0AbQBlAG4AdAAgACoALwAKAHsAfQAgAGYAaQBuAGEAbABsAHkAIAB7AH0A

**Review by ematipico — CHANGES_REQUESTED** [review]
Thank you for looking after it!

Could please create a new test case in our test suite and use the prettier code that Micha pasted in the issue? 

We want to use Prettier's output and make sure it doesn't change. If it's different, it means that we did something wrong. If it doesn't, we reached the compability!

File: crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap (hunk 7 above)
Comment (ematipico) [reply crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap:31]: You can check the prettier snapshot and see what they do there

File: crates/rome_js_formatter/src/js/auxiliary/default_clause.rs [hunk 8]
```diff
@@ -15,16 +16,32 @@ impl FormatNode for JsDefaultClause {
...
+        };
         let default = default_token.format(formatter)?;
         let colon = colon_token.format(formatter)?;
         let statements = formatter.format_list(consequent);
 
+        let cons = if statements.is_empty() {
+            // Skip inserting an indent block is the consequent is empty to print
+            // the trailing comments for the case clause inline if there is no
+            // block to push them into
+            hard_line_break()
```
[the remark this answers is not in the document]
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/js/auxiliary/default_clause.rs:32]: > The comment is really difficult to read... could you please revisit it, or use some commas or dots?

Sorry, this PR is still WIP, I will rewrite the comments after I passed the test case

**Comment by ematipico** [comment]
> ```shell
> test specs::prettier::typescript::webhost::webtsc ... ok
> 
> failures:
> 
> ---- specs::prettier::js::try_::try_ stdout ----
> Differences (-input|+output):
>                          Line(Hard),
>                          SyntaxTokenSlice("/* missing comment */"),
>                          Line(Hard),
>                      ],
>                  ),
> -                Group(
> -                    List [
> -                        SyntaxTokenSlice("{"),
> -                        SyntaxTokenSlice("}"),
> -                    ],
> -                ),
> +                SyntaxTokenSlice("{"),
> +                Line(Hard),
> +                SyntaxTokenSlice("}"),
>                  Space,
>                  SyntaxTokenSlice("finally"),
>                  Space,
>                  SyntaxTokenSlice("{"),
>                  Line(Hard),
> 
> thread 'main' panicked at 'assertion failed: `(left == right)`'
>   left: `"try\n/* missing comment */\n{} finally {\n}\n"`
>  right: `"try\n/* missing comment */\n{\n} finally {\n}\n"`
> 
> Differences (-left|+right):
>  try
>  /* missing comment */
> -{} finally {
> +{
> +} finally {
>  }
> 
> ', crates/rome_js_formatter/tests/check_reformat.rs:60:9
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
>    1: core::panicking::panic_fmt
>              at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
>    2: prettier_tests::check_reformat::check_reformat
>              at ./tests/check_reformat.rs:60:9
>    3: prettier_tests::test_snapshot
>              at ./tests/prettier_tests.rs:95:17
>    4: prettier_tests::specs::prettier::js::try_::try_
>              at ./tests/prettier_tests.rs:23:1
>    5: prettier_tests::specs::prettier::js::try_::try_::{{closure}}
>              at ./tests/prettier_tests.rs:23:1
>    6: core::ops::function::FnOnce::call_once
>              at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
>    7: core::ops::function::FnOnce::call_once
>              at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 
> 
> failures:
>     specs::prettier::js::try_::try_
> ```
> 
> @ematipico This is the only test case I failed, but I don't know how to change the test case, actually, the new test result should be alright, according to prettier [play.rome.tools/?lineWidth=80&indentStyle=tab"eStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#dAByAHkACgAvACoAIABtAGkAcwBzAGkAbgBnACAAYwBvAG0AbQBlAG4AdAAgACoALwAKAHsAfQAgAGYAaQBuAGEAbABsAHkAIAB7AH0A](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#dAByAHkACgAvACoAIABtAGkAcwBzAGkAbgBnACAAYwBvAG0AbQBlAG4AdAAgACoALwAKAHsAfQAgAGYAaQBuAGEAbABsAHkAIAB7AH0A)

It seems that the `try {}` part is not correct yet, probably because your new code it's not handling it. If you added it, maybe it should fix the issue

File: crates/rome_js_formatter/src/js/auxiliary/default_clause.rs [hunk 9]
```diff
@@ -15,16 +16,32 @@ impl FormatNode for JsDefaultClause {
             consequent,
         } = self.as_fields();
 
+        let syntax_node = consequent.syntax();
+        let is_first_child_block_stmt = match syntax_node.first_child() {
+            Some(stmt) => stmt.kind() == JsSyntaxKind::JS_BLOCK_STATEMENT,
+            None => false,
+        };
```
[the remark this answers is not in the document]
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/js/auxiliary/default_clause.rs:23]: It can't, `can_cast` must pass a `LanguageKind`. first_child return a `Option<SyntaxNode>`, you need to `unwrap` it.

[the remark this answers is not in the document]
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/js/auxiliary/default_clause.rs:23]: I change it to `let first_child_is_block_stmt = matches!(syntax_node.first_child().map(|n| n.kind()), Some(JsSyntaxKind::JS_BLOCK_STATEMENT));`

File: crates/rome_js_formatter/src/js/statements/block_statement.rs [hunk 10]
```diff
@@ -44,13 +45,51 @@ fn is_non_collapsable_empty_block(block: &JsBlockStatement) -> bool {
...
+    // ```
+    // for the second time, the function would return true, because the block is empty and `parent.syntax.kind` is  `JS_TRY_FINALLY_STATEMENT`, which would hit the branch `Some(_) => true`,
+    // finally the code would be formatted as:
+    // ```js
+    // try
+    /* missing comment */
+    // {
+    // } finally {
+    // }
+    // ```
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/src/js/statements/block_statement.rs:72]: I explain here why the test would fail before

File: crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap (hunk 7 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap:31]: > You can check the prettier snapshot and see what they do there

They would do nothing since this code snippet has a syntax error

File: crates/rome_js_formatter/src/js/auxiliary/default_clause.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (ematipico) [reply crates/rome_js_formatter/src/js/auxiliary/default_clause.rs]: Also this works, we use it across the board :)

File: crates/rome_js_formatter/tests/specs/js/module/statement/switch.js [hunk 11]
```diff
@@ -13,3 +13,7 @@ switch (key) {
 
 
 }
+
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/js/module/statement/switch.js:16]: @ematipico The code snippet of https://github.com/rome/tools/issues/2407, I have added here

File: crates/rome_js_formatter/src/js/statements/block_statement.rs [hunk 12]
```diff
@@ -48,9 +48,21 @@ fn is_non_collapsable_empty_block(block: &JsBlockStatement) -> bool {
...
+            | JsSyntaxKind::TS_MODULE_DECLARATION
+            | JsSyntaxKind::TS_DECLARE_FUNCTION_DECLARATION,
+        ) => false,
+        // Some(JsSyntaxKind::JS_CATCH_CLAUSE) => {
+        //     let parent = block.syntax().parent().unwrap();
+        //     matches!(parent.parent().map(|p| p.kind()), Some(JsSyntaxKind::JS_FINALLY_CLAUSE))
+        // }
+        Some(_) => true,
+        None => false,
+    }
```
[the remark this answers is not in the document]
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/js/statements/block_statement.rs]: According to prettier code logic, try_statement is not needed.

**Comment by IWANABETHATGUY** [comment]
!bench_formatter

**Comment by IWANABETHATGUY** [comment]
> 
I have dded here
https://github.com/rome/tools/pull/2514/files/cffe4b0aab04dac6f7c766d466497a9143eedcc1#diff-045304d54c7a2918b16b74ec1b51504113cb8479c67a7d6e28b54502078d44c6R16-R19

File: crates/rome_js_formatter/src/js/auxiliary/case_clause.rs [hunk 13]
```diff
@@ -16,7 +18,11 @@ impl FormatNode for JsCaseClause {
             colon_token,
             consequent,
         } = self.as_fields();
-
+        let syntax_node = consequent.syntax();
+        let is_first_child_block_stmt = match syntax_node.first_child() {
+            Some(stmt) => stmt.kind() == JsSyntaxKind::JS_BLOCK_STATEMENT,
+            None => false,
+        };
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/js/auxiliary/case_clause.rs:25]: You can use a match here. `matches!(consequent, JsAnyStatement::JsBlockStatement(_))`

File: crates/rome_js_formatter/src/js/auxiliary/default_clause.rs [hunk 14]
```diff
@@ -15,16 +16,31 @@ impl FormatNode for JsDefaultClause {
             consequent,
         } = self.as_fields();
 
+        let syntax_node = consequent.syntax();
+
+        let first_child_is_block_stmt = matches!(
+            syntax_node.first_child().map(|n| n.kind()),
+            Some(JsSyntaxKind::JS_BLOCK_STATEMENT)
+        );
+
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/js/auxiliary/default_clause.rs:25]: Same here, use a `match` that tests directly on the `JsAnyStatement`

File: crates/rome_js_formatter/src/js/statements/block_statement.rs [hunk 15]
```diff
@@ -44,13 +45,51 @@ fn is_non_collapsable_empty_block(block: &JsBlockStatement) -> bool {
...
+    // ```
+    if !block.statements().is_empty()
+        && block
+            .statements()
+            .iter()
+            .any(|s| !matches!(s, JsAnyStatement::JsEmptyStatement(_)))
+    {
         return false;
     }
+    // reference https://github.com/prettier/prettier/blob/main/src/language-js/print/block.js#L19
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/js/statements/block_statement.rs:81]: This link will point to an invalid line if the `block.js` file ever changes. 

Open the link, click on the three dots button shown next to line 19 and select: "Copy permalink". Use that link instead.

File: crates/rome_js_formatter/src/js/statements/block_statement.rs [hunk 16]
```diff
@@ -44,13 +45,51 @@ fn is_non_collapsable_empty_block(block: &JsBlockStatement) -> bool {
     {
         return false;
     }
-
-    if !block.statements().is_empty() {
+    // add extra branch to avoid formatting the same code twice and generating different code,
+    // here is a example:
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/js/statements/block_statement.rs:49]:
```suggestion
    // here is an example:
```

File: crates/rome_js_formatter/src/js/statements/block_statement.rs [hunk 17]
```diff
@@ -44,13 +45,51 @@ fn is_non_collapsable_empty_block(block: &JsBlockStatement) -> bool {
...
+    /* missing comment */
+    // {
+    // } finally {
+    // }
+    // ```
+    if !block.statements().is_empty()
+        && block
+            .statements()
+            .iter()
+            .any(|s| !matches!(s, JsAnyStatement::JsEmptyStatement(_)))
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/js/statements/block_statement.rs:77]: What's the formatted output of the case you explain in the example above with this branch in place?

File: crates/rome_js_formatter/src/js/auxiliary/default_clause.rs [hunk 18]
```diff
@@ -15,16 +16,31 @@ impl FormatNode for JsDefaultClause {
...
+            format_elements![space_token(), statements]
+        } else {
+            // no line break needed after because it is added by the indent in the switch statement
+            indent(format_elements![hard_line_break(), statements])
+        };
         Ok(format_elements![
             default,
             colon,
             space_token(),
             // no line break needed after because it is added by the indent in the switch statement
```
Comment (leops) [inline crates/rome_js_formatter/src/js/auxiliary/default_clause.rs:42]: Nit: this outdated comment can be removed

Comment (leops) [inline crates/rome_js_formatter/src/js/auxiliary/default_clause.rs:42]: Nit: this outdated comment can be removed

**Review by ematipico — APPROVED** [review]
It seems that the formatting is consistent with prettier! I double checked in their playground because it's not easy to see it from this test suite

File: crates/rome_js_formatter/tests/specs/prettier/typescript/catch-clause/type-annotation.ts.snap [hunk 19]
```diff
@@ -16,9 +15,13 @@ catch (e: unknown) {}
...
 ```js
-try {} catch (e: any) {}
+try {
+} catch (e: any) {
+}
 
-try {} catch (e: unknown) {}
+try {
+} catch (e: unknown) {
+}
```
Comment (mrkldshv) [inline crates/rome_js_formatter/tests/specs/prettier/typescript/catch-clause/type-annotation.ts.snap:24]: @ematipico I guess we have minor divergence from prettier in this case. Should we handle this case?

Prettier output: 
```js
try {
} catch (e: any) {}

try {
} catch (e: unknown) {}
```
Playground link: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBPABMAOlAXyzAEMYwALLACjiSxKgwEod8D991s9DizKNOlgCuUANZQIAdyiteBEABoQEAA4wAltADOyUCTRoZABUMI9KEgBtpJDHpUAjNCTDi4MAMokAtnAAZTSg4ZAAzGx04Z1d3Ty81N2CAc2R0EWiQOF8nOAATPPyAxmSREmS4ADEINF8yLShUqxEYCGUQChhfawB1Ck14HUSwOC8LAc0ANwGMZHAdRxBgqLQYE1dkuvDIzIArHQAPLxTrOABFEQh4besolUS0FbmYDDU4HTA0TQ12tS-YHqaPIwCjIAAcAAZ7sYoj1XGo5n93nA0JNQioAI6XeDrdSWEAkHQAWhC+Xy7TQcCxmkp63KWyQEVumSivk0aTQGRUOhO52xoUZOxUMBITkBwNBSAATMLXJprCkAMIQXwMrI6ACs7REUQAKqLLEy7iBJhkAJJQQqwLyfb4wACClq8L1ONyiBAIQA

File: crates/rome_js_formatter/src/js/statements/block_statement.rs (hunk 17 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/js/statements/block_statement.rs:77]: add an extra branch to avoid formatting the same code twice and generating different code,
 here is an example:
```js
try
 /* missing comment */
 {;}
finally {}
```

 if we don't add the extra branch, this function will return false, because  `block.statement` has one empty statement,
 and would be formatted as :
```js
 try
/* missing comment */
{}
finally {}
```
 for the second time, the function would return true, because the block is empty and `parent.syntax.kind` is  `JS_TRY_FINALLY_STATEMENT`, which would hit the branch `Some(_) => true`,
     finally, the code would be formatted as:

```js
 try
/* missing comment */
 {
 } finally {
 }
```

I also commented on codebase

Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/js/statements/block_statement.rs:77]: https://github.com/IWANABETHATGUY/tools/blob/7b560b65da1ca22d6bab1fbb63c8a948f081a1c8/crates/rome_js_formatter/src/js/statements/block_statement.rs#L48

File: crates/rome_js_formatter/tests/specs/prettier/typescript/catch-clause/type-annotation.ts.snap (hunk 19 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/tests/specs/prettier/typescript/catch-clause/type-annotation.ts.snap]: Fixed

**Comment by ematipico** [comment]
Amazing work @IWANABETHATGUY ! Thank you very much for your contribution!
