### PR TITLE
fix: apply chmod at pkg creation time

### LINKED ISSUE #3799: 🐛 chmod should be performed at pkg creation time instead of with postinstall hook
### Environment information

```block
yarn run v1.22.15
$ /home/castarco/Code/pencil4ts/node_modules/.bin/rome rage
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   linux

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       1
  Client Name:          Visual Studio Code
  Client Version:       1.73.1

Workspace:
  Open Documents:       1
  Client Name:          Visual Studio Code
  Client Version:       1.73.1

Rome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

├─1632175ms INFO rome_lsp::server Starting Rome Language Server...

Done in 0.12s.
```

### What happened?

1. I had disabled `postinstall` scripts  in my `.npmrc` file, to avoid/mitigate potential security issues.
2. When I installed `rome`, I found it was failing. The reason was that the binary being called was not executable. After digging a bit, I discovered that this was happening because its "executable" flag depended on a `postinstall` hook being executed.

### Expected result

The packaged binary should be executable from the very beginning. This can be done at packaging time, removing the need to call any `postinstall` hook.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by castarco**
## Summary

- Apply chmod at package creation time instead of doing it when running the postinstall hook.
- I did not disabled postinstall hook entirely because it can give interesting information to users, I just removed the part where it applies chmod (because it's supposed to be done before, at package creation time).

Fixes #3799 .

## Test Plan

Testing this change is not trivial because it impacts CD pipelines. My suggestion:
1. make an alpha/beta/rc release, to avoid risking users' installations.
2. Modify your local `.npmrc` file, by adding this line: `ignore-scripts=true`
3. Install this alpha/beta/rc package version, and check that the installed binary has execution permissions, even when the `postinstall` hook has not been triggered because of our change on the `.npmrc` config file.

As a side note, it would be great if some of the steps that are being executed in the CD pipeline were extracted into scripts that we could run locally. This way it would be easier to test some of these details. I'm not doing that in this PR because I believe it deserves some prior discussion, and I don't want to mix too many things in a single PR.

---

Signed-off-by: Andres Correa Casablanca <castarco@coderspirit.xyz>

### CODE REVIEW

File: npm/rome/scripts/generate-packages.mjs [hunk 1]
```diff
@@ -44,6 +44,7 @@ function generateNativePackage(platform, arch) {
 
 	console.log(`Copy binary ${binaryTarget}`);
 	fs.copyFileSync(binarySource, binaryTarget);
+	fs.chmodSync(binaryTarget, 0o755);
```
Comment (castarco) [inline npm/rome/scripts/generate-packages.mjs:47]: The same way there is a `try-catch` block for the `chmodSync` call in the `postinstall` hook code, we could do the same here, because in theory it can fail the same way. However, that applies to every IO operation in this script (like `copy`), but that's not done here (I guess because it doesn't improve much on the potential error messages we could have, and because the pipeline would have crashed anyway).

File: npm/rome/scripts/postinstall.js [hunk 2]
```diff
@@ -25,17 +25,6 @@ if (binName) {
 			`The Rome CLI postinstall script failed to resolve the binary file "${binName}". Running Rome from the npm package will probably not work correctly.`,
 		);
 	}
-
-	if (binPath) {
```
Comment (MichaReiser) [inline npm/rome/scripts/postinstall.js:29]: Would it make sense to move the resolution failure messages to the rome start script instead and avoid using postinstall scripts altogether?

**Review by MichaReiser — COMMENTED** [review]
Nice. Didn't know that npm preserves execution permissions. 

I wasn't able to find any documentation but [this old issue](https://github.com/npm/npm/issues/18324) confirms that it used to work (and should be fixed by now). 

This may fix https://github.com/rome/tools/issues/3621

File: npm/rome/scripts/postinstall.js (hunk 2 above)
Comment (leops) [reply npm/rome/scripts/postinstall.js:29]: The `rome` script already implements one out of the two error messages in the postinstall hook, so we could bring them in sync. But I still think we should keep that script, the call to `chmod` was only added there as a hack but its original purpose was to check that Rome is installed correctly and immediately alert the user if an issue was found, instead of having to wait for them to run the `rome` command.

**Review by leops — APPROVED** [review]
