### PR TITLE
fix(rome_js_analyze): #4410

### LINKED ISSUE #4410: 🐛 `lint/a11y/useButtonType` misses some issues
### Environment information

https://docs.rome.tools/playground/?indentStyle=space&lintRules=all&code=PAA%2BAAoAIAAgAHsALwAqACAAZwBvAG8AZAAgACoALwB9AAoAIAAgADwAYgB1AHQAdABvAG4APgB0AGUAcwB0ADwALwBiAHUAdAB0AG8AbgA%2BAAoAIAAgADwAYgB1AHQAdABvAG4AIAB0AHkAcABlAD0AIgBpAG4AdgBhAGwAaQBkACIAPgB0AGUAcwB0ADwALwBiAHUAdAB0AG8AbgA%2BAAoAIAAgADwAYgB1AHQAdABvAG4AIAB0AHkAcABlAD0AIgBpAG4AdgBhAGwAaQBkACIAIABvAG4AQwBsAGkAYwBrAD0AewBuAHUAbABsAH0APgB0AGUAcwB0ADwALwBiAHUAdAB0AG8AbgA%2BAAoAIAAgAHsALwAqACAAYgBhAGQALAAgAHQAaABlAHMAZQAgAHMAaABvAHUAbABkACAAYgBlACAAYwBhAHUAZwBoAHQAIABhAHMAIAB3AGUAbABsACAAKgAvAH0ACgAgACAAPABiAHUAdAB0AG8AbgAgAC8APgAKACAAIAA8AGIAdQB0AHQAbwBuACAAbwBuAEMAbABpAGMAawA9AHsAbgB1AGwAbAB9ACAALwA%2BAAoAIAAgADwAYgB1AHQAdABvAG4AIABvAG4AQwBsAGkAYwBrAD0AewBuAHUAbABsAH0APgB0AGUAcwB0ADwALwBiAHUAdAB0AG8AbgA%2BAAoAIAAgADwAYgB1AHQAdABvAG4AIAB0AHkAcABlAD0AIgBpAG4AdgBhAGwAaQBkACIAIAAvAD4ACgAgACAAPABiAHUAdAB0AG8AbgAgAHQAeQBwAGUAPQAiAGkAbgB2AGEAbABpAGQAIgAgAG8AbgBDAGwAaQBjAGsAPQB7AG4AdQBsAGwAfQAgAC8APgAKADwALwA%2BADsACgA%3D

### What happened?

1. Open playground link
2. Notice that some buttons should be flagged for missing/invalid `type` prop

### Expected result

Parity with https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/button-has-type.md

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #4410 and make the rule more robust by handling more cases such as:

```jsx
<button type/>
```

I also made some refactoring to simplify the implementation.

## Test Plan

New tests and regression tests included.

## Changelog

- [x] The PR requires a changelog line

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

File: crates/rome_js_analyze/tests/specs/a11y/useButtonType/inJsx.jsx [hunk 1]
```diff
@@ -2,11 +2,19 @@
 <>
     <button>do something</button>
     <button type="bar">do something</button>
+    <button type>do something</button>
+    <button/>
```
Comment (ematipico) [inline crates/rome_js_analyze/tests/specs/a11y/useButtonType/inJsx.jsx:6]: Are self-closing buttons a thing in JSX?

**Review by ematipico — APPROVED** [review]
Looks good to me. Rule caught some cases in our playground that we should fix :D
