### PR TITLE
fix(noRedeclare): allow merging namespace + variable

### LINKED ISSUE #4771: 🐛 bug(lint/noRedeclare): false positive for namespace + variable declaration merging
UPDATE: Made a PR to add test case and fix: #4772 

### Environment information

```block
CLI:
  Version:                      12.1.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-kitty"
  JS_RUNTIME_VERSION:           "v20.3.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "null"

Rome Configuration:
  Status:                       unset
```

### What happened?

1. In the wild: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/body-parser/index.d.ts . `declare const bodyParser: bodyParser.BodyParser;` is incorrectly flagged as a redeclaration, but actually it's a declaration merge.
2. This test case passes for `typescript-eslint`: https://github.com/llllvvuu/typescript-eslint/blob/15477dc3e12450bb70dca7cf71f17752e0f075ca/packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts#L75
3. `tsc` reports no errors and performs the declaration merge successfully, so Rome should also report no errors.

### Expected result

No linter error.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by llllvvuu**
fixes #4771

Note: [`tsc` doesn't always allow merging namespaces and variables](https://github.com/microsoft/TypeScript/issues/55190#issuecomment-1684904258). Either way, checking this shouldn't fall under the linter - either it's a type error or it's a declaration merge, but it's never a shadow.

### CODE REVIEW

File: crates/rome_js_analyze/tests/specs/suspicious/noRedeclare/valid-declaration-merging.ts [hunk 1]
```diff
@@ -69,6 +69,18 @@ export namespace Orientation {
...
+	interface BodyParser {
+		/** @deprecated */
+		(): void
+	}
+	interface Options {
+		inflate?: boolean | undefined
+	}
+}
+declare const bodyParser: bodyParser.BodyParser
+
```
Comment (Conaclos) [inline crates/rome_js_analyze/tests/specs/suspicious/noRedeclare/valid-declaration-merging.ts:83]: Could you add an example with a concrete variable?

Something like:

```ts
namespace A {}
const A = {}
```

**Review by Conaclos — CHANGES_REQUESTED** [review]

**Comment by Conaclos** [comment]
> Note: [`tsc` doesn't always allow merging namespaces and variables](https://github.com/microsoft/TypeScript/issues/55190#issuecomment-1684904258). Either

I was not aware of the merging capability between a variable and an only-type namespace.
For now the fix looks fair.

**Comment by llllvvuu** [comment]
Yes, TypeScript is very weird 😂 Concrete variable example added!

**Review by Conaclos — APPROVED** [review]
Thanks!
