### PR TITLE
fix: regressions in decisions and review command

### LINKED ISSUE #1579: 🐛 Regressions in `check --review` command
## Environment

<details>
<summary>$ rome rage --summary</summary>

```
Environment Variables
  {COLORTERM: "truecolor", LANG: "en_US.UTF-8", TERM: "xterm-256color", TERM_PROGRAM: "vscode"}

User Config
  unset

Rome Version
  10.0.7-beta.18

Node Version
  14.17.0

Platform
  darwin x64 19.6.0

Terminal Features
  {
    background: "unknown"
    colorDepth: 24
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<147>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</Users/Yasser/Dev/rome>
    realCwd: AbsoluteFilePath</Users/Yasser/Dev/rome>
  }

Server Status
  {
    projects: [{id: 0}, {id: 1}]
    workers: [{astCacheSize: 0, heapTotal: 46_845_952, ownedBytes: 0n, ownedFileCount: 0, pid: 57_884, uptime: 0.570365222}]
    server: {heapTotal: 46_845_952, pid: 57_884, uptime: 0.570518524}
  }

```
</details>

## Steps To Reproduce

1. Create a file `test.ts` containing:
```js
const foo = true;
if (foo == false) {
	console.log("Impossible!");
}
```
2. Running `rome check test.ts --review` briefly scrolls past a diagnostic then clears the terminal and displays:
```
 Reviewing diagnostics (1/1) 

❯ How do you want to resolve this?
ℹ Use arrow keys and then enter to select an option
  ◉ Add suppression comment (shortcut s)
  ◯ Do nothing (shortcut n)
  ◯ Exit (shortcut escape)
  ◯ More options... (shortcut m)
```
3. Selecting "Add suppression comment" results in:
```js
const foo = true;
// rome-ignore lint/js/noDoubleEquals: suppressed via --review
if (
	// rome-ignore lint/js/noDoubleEquals: suppressed via --review
	foo ==
	// rome-ignore lint/js/noDoubleEquals: suppressed via --review
	false
) // rome-ignore lint/js/noDoubleEquals: suppressed via --review
{
	console.log("Impossible!");
}
```

## Expected Results

  - The diagnostic should still be visible while the user is making a choice.
  - There should be an option to apply the suggested auto-fix for `lint/js/noDoubleEquals`
  - Selecting the option to add a suppression comment should only add one suppression comment.

### PR DESCRIPTION
**Pull request by yassere**
## Summary

Closes #1579 

- Include `verboseAdvice` options when reviewing diagnostics
- Display the diagnostic that the user is being asked to review
- Fix `less` option so that it toggles back to original options
- Prevent injecting multiple duplicate suppression comments

### CODE REVIEW

**Review by ematipico — APPROVED** [review]

File: internal/numbers/indexed.ts [hunk 1]
```diff
@@ -82,6 +83,15 @@ enhanceNodeInspectClass(
...
 );
 
+export class IndexedNumberSet<Indexed extends IndexedNumber>
+	extends MappedSet<Indexed, number> {
+	constructor(entries?: Iterable<Indexed>) {
+		super((line) => [line.valueOf(), line], entries);
+	}
+}
+
+IndexedNumberSet.prototype[Symbol.toStringTag] = "IndexedNumberSet";
```
Comment (jamiebuilds) [inline internal/numbers/indexed.ts:93]: This seems like a very one-off data structure. Do you think it would be bad just to use `MappedSet` directly above?

```js
const visitedLines = new MappedSet<OneIndexed, number>();
```

Comment (yassere) [reply internal/numbers/indexed.ts:93]: I don't think it's bad, but it would have to be constructed like this:
```js
const visitedLines = new MappedSet<OneIndexed, number>((line) => [
	line.valueOf(),
	line,
]);
```

My thought was that there might be other situations where we want to track a set of lines or positions and we wouldn't have to duplicate the serialize function in that case.

If this is just going to be a one-off, would it be simpler to make it a `Set<number>` and just add/check membership as `line.valueOf()`?

Comment (yassere) [reply internal/numbers/indexed.ts:93]: Although I realize now that I shouldn't have named the parameter `line` in the serialize function in `IndexedNumberSet`. I'd originally implemented this by using `MappedSet` directly and then I just copied over the serializer when I extracted it.

Comment (yassere) [reply internal/numbers/indexed.ts]: I'll merge this for now (with the renamed parameter). I think we can revisit this once the `IndexedNumber` abstraction is changed for #1548
