### PR TITLE
fix(rome_js_analyze): improve the detection of `ReactDOM.render` calls in `noRenderReturnValue`

### LINKED ISSUE #3617: 🐛 `noRenderReturnValue` incorrectly flags non React render calls
### Environment information

```block
Rome v10
```

### What happened?

Rome incorrectly flags the use of the result of the following `render` call

```javascript
function render(value) {
  return `Rendered: ${value}`
}

function test() {
  const result = render(a);
  
}
```

[Playground](https://play.rome.tools/?code=function+render%28value%29+%7B%0A++return+%60Rendered%3A+%24%7Bvalue%7D%60%0A%7D%0A%0Afunction+test%28%29+%7B%0A++const+result+%3D+render%28a%29%3B%0A++%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=false&jsx=true#ZgB1AG4AYwB0AGkAbwBuACAAcgBlAG4AZABlAHIAKAB2AGEAbAB1AGUAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIABgAFIAZQBuAGQAZQByAGUAZAA6ACAAJAB7AHYAYQBsAHUAZQB9AGAACgB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIAB0AGUAcwB0ACgAKQAgAHsACgAgACAAYwBvAG4AcwB0ACAAcgBlAHMAdQBsAHQAIAA9ACAAcgBlAG4AZABlAHIAKABhACkAOwAKACAAIAAKAH0A)

### Expected result

Rome should only flag `render` calls that resolve to React's render function.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

Fixes #3617

This refactors the `noRenderReturnValue` rule to use `is_react_call_api` to detect calls to `ReactDOM.render`. This includes extending `is_react_call_api` to support detecting symbols imported from `react-dom` in addition to the `react` package.

## Test Plan

I've extended the tests for the `noRenderReturnValue` to have cases with and without an import statement, and check for regressions of the false positive case described in #3617

### CODE REVIEW

File: crates/rome_js_analyze/src/react.rs [hunk 1]
```diff
@@ -216,6 +218,28 @@ impl ReactApiCall for ReactCloneElementCall {
...
 }
 
+#[derive(Debug, Clone, Copy)]
+pub(crate) enum ReactLibrary {
+    React,
+    ReactDOM,
+}
+
+impl ReactLibrary {
+    fn import_name(self) -> &'static str {
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/react.rs:228]: nit
```suggestion
   const fn import_name(self) -> &'static str {
```

**Review by MichaReiser — APPROVED** [review]
I may have missed it. Did you add a test for the case where the user defines a custom `render` function?

**Comment by leops** [comment]
> I may have missed it. Did you add a test for the case where the user defines a custom `render` function?

Good catch, I did add it originally but it got lost when I split out the single test files into multiple modules
