### PR TITLE
fix(rome_lsp): improve the pattern matching logic for ignored files

### LINKED ISSUE #3790: 🐛 LSP ignores `ignore`s
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 unset

Rome Configuration:
  Status:               loaded
  Formatter disabled:   true
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   windows

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       5
  Client Name:          Visual Studio Code
  Client Version:       1.73.1

Rome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─141334249ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─141346149ms INFO rome_service::configuration Attempting to load the configuration file at path "d:\\repo\\rome.json"
├─┐rome_fs::fs::os::OsFile::read_to_string{}
├─┘
├─141346149ms INFO rome_lsp::session Configuration found, and it is valid!
├─┐rome_lsp::session::update_workspace_settings{}
│ ├─┐rome_service::workspace::server::update_settings{params=UpdateSettingsParams { configuration: Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) } }}
│ │ ├─┐rome_service::settings::merge_with_configuration{configuration=Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) }}
│ │ ├─┘
│ ├─┘
├─┘
├─141346568ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(8)}
├─┘
├─141347250ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─141350661ms INFO tower_lsp::service::layers shutdown request received, shutting down
├─141350661ms INFO tower_lsp::service::layers exit notification received, stopping
├─141350694ms INFO rome_lsp::server Starting Rome Language Server...
├─141350694ms INFO rome_lsp::server Attempting to load the configuration from 'rome.json' file
├─141350694ms INFO rome_service::configuration Attempting to load the configuration file at path "d:\\repo\\rome.json"
├─┐rome_fs::fs::os::OsFile::read_to_string{}
├─┘
├─141350694ms INFO rome_lsp::session Configuration found, and it is valid!
├─┐rome_js_parser::parse::parse{file_id=FileId(0)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(1)}
├─┘
├─┐rome_lsp::session::update_workspace_settings{}
│ ├─┐rome_service::workspace::server::update_settings{params=UpdateSettingsParams { configuration: Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) } }}
│ │ ├─┐rome_service::settings::merge_with_configuration{configuration=Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) }}
│ │ ├─┘
│ ├─┘
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(2)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─141354385ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─141355415ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─141360965ms INFO rome_service::configuration Attempting to load the configuration file at path "d:\\repo\\rome.json"
├─┐rome_fs::fs::os::OsFile::read_to_string{}
├─┘
├─141360965ms INFO rome_lsp::session Configuration found, and it is valid!
├─┐rome_lsp::session::update_workspace_settings{}
│ ├─┐rome_service::workspace::server::update_settings{params=UpdateSettingsParams { configuration: Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) } }}
│ │ ├─┐rome_service::settings::merge_with_configuration{configuration=Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) }}
│ │ ├─┘
│ ├─┘
├─┘
├─141362667ms INFO tower_lsp::service::layers shutdown request received, shutting down
├─141362668ms INFO tower_lsp::service::layers exit notification received, stopping
├─141362696ms INFO rome_lsp::server Starting Rome Language Server...
├─141362697ms INFO rome_lsp::server Attempting to load the configuration from 'rome.json' file
├─141362697ms INFO rome_service::configuration Attempting to load the configuration file at path "d:\\repo\\rome.json"
├─┐rome_fs::fs::os::OsFile::read_to_string{}
├─┘
├─141362697ms INFO rome_lsp::session Configuration found, and it is valid!
├─┐rome_js_parser::parse::parse{file_id=FileId(0)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(1)}
├─┘
├─┐rome_lsp::session::update_workspace_settings{}
│ ├─┐rome_service::workspace::server::update_settings{params=UpdateSettingsParams { configuration: Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) } }}
│ │ ├─┐rome_service::settings::merge_with_configuration{configuration=Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) }}
│ │ ├─┘
│ ├─┘
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(2)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─141363573ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─141384096ms INFO rome_service::configuration Attempting to load the configuration file at path "d:\\repo\\rome.json"
├─┐rome_fs::fs::os::OsFile::read_to_string{}
├─┘
├─141384097ms INFO rome_lsp::session Configuration found, and it is valid!
├─┐rome_lsp::session::update_workspace_settings{}
│ ├─┐rome_service::workspace::server::update_settings{params=UpdateSettingsParams { configuration: Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Off), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) } }}
│ │ ├─┐rome_service::settings::merge_with_configuration{configuration=Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Off), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) }}
│ │ ├─┘
│ ├─┘
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─141384731ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─141385664ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─141388418ms INFO rome_service::configuration Attempting to load the configuration file at path "d:\\repo\\rome.json"
├─┐rome_fs::fs::os::OsFile::read_to_string{}
├─┘
├─141388418ms INFO rome_lsp::session Configuration found, and it is valid!
├─┐rome_lsp::session::update_workspace_settings{}
│ ├─┐rome_service::workspace::server::update_settings{params=UpdateSettingsParams { configuration: Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) } }}
│ │ ├─┐rome_service::settings::merge_with_configuration{configuration=Configuration { files: None, formatter: Some(FormatterConfiguration { enabled: false, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(false), a11y: Some(A11y { recommended: None, rules: {"noAutofocus": Plain(Off), "noPositiveTabindex": Plain(Warn), "useAltText": Plain(Warn), "useAnchorContent": Plain(Warn), "useBlankTarget": Plain(Warn), "useButtonType": Plain(Warn), "useKeyWithClickEvents": Plain(Off), "useKeyWithMouseEvents": Plain(Off), "useValidAnchor": Plain(Off)} }), complexity: Some(Complexity { recommended: None, rules: {"noExtraBooleanCast": Plain(Warn), "useSimplifiedLogicExpression": Plain(Off)} }), correctness: Some(Correctness { recommended: None, rules: {"noArguments": Plain(Warn), "noArrayIndexKey": Plain(Off), "noAsyncPromiseExecutor": Plain(Warn), "noCatchAssign": Plain(Warn), "noChildrenProp": Plain(Off), "noCommentText": Plain(Warn), "noCompareNegZero": Plain(Warn), "noDebugger": Plain(Warn), "noDelete": Plain(Warn), "noDoubleEquals": Plain(Warn), "noDupeArgs": Plain(Warn), "noEmptyPattern": Plain(Warn), "noFunctionAssign": Plain(Warn), "noImportAssign": Plain(Warn), "noLabelVar": Plain(Warn), "noMultipleSpacesInRegularExpressionLiterals": Plain(Warn), "noNewSymbol": Plain(Off), "noRenderReturnValue": Plain(Warn), "noRestrictedGlobals": Plain(Off), "noShadowRestrictedNames": Plain(Warn), "noSparseArray": Plain(Warn), "noUndeclaredVariables": Plain(Off), "noUnnecessaryContinue": Plain(Warn), "noUnreachable": Plain(Off), "noUnsafeNegation": Plain(Warn), "noUnusedVariables": Plain(Off), "noUselessFragments": Plain(Off), "noVoidElementsWithChildren": Plain(Warn), "useSingleCaseStatement": Plain(Off), "useValidTypeof": Plain(Warn), "useWhile": Plain(Warn)} }), nursery: None, security: Some(Security { recommended: None, rules: {"noDangerouslySetInnerHtml": Plain(Warn), "noDangerouslySetInnerHtmlWithChildren": Plain(Warn)} }), style: Some(Style { recommended: None, rules: {"noImplicitBoolean": Plain(Off), "noNegationElse": Plain(Off), "noShoutyConstants": Plain(Warn), "noUnusedTemplateLiteral": Plain(Warn), "useBlockStatements": Plain(Off), "useFragmentSyntax": Plain(Warn), "useOptionalChain": Plain(Warn), "useSelfClosingElements": Plain(Warn), "useShorthandArrayType": Plain(Warn), "useSingleVarDeclarator": Plain(Warn), "useTemplate": Plain(Warn)} }) }), ignore: Some({"./coverage/**/*", "./node_modules/**/*"}) }), javascript: Some(JavascriptConfiguration { formatter: Some(JavascriptFormatter { quote_style: Single, quote_properties: AsNeeded, trailing_comma: None }), globals: None }) }}
│ │ ├─┘
│ ├─┘
├─┘
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─141392119ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─┐rome_js_parser::parse::parse{file_id=FileId(3)}
├─┘
├─141392899ms WARN tower_lsp Got a textDocument/didSave notification, but it is not implemented
├─┐rome_js_parser::parse::parse{file_id=FileId(4)}
├─┘
├─141476185ms INFO rome_lsp::server Starting Rome Language Server...
```

### What happened?

1. Add `ignore` settings for both formatter and linter
2. Open a file that should be ignored
3. Rome will allow formatting/linting it in VSCode

### Expected result

Rome's VSCode extension should respect the `ignore` settings in `rome.json`.
The CLI works fine in that regard.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

Fixes #3790

This PR fixes how ignore patterns are parsed and changes how paths are represented in the language server to reduce discrepancies with the CLI. For ignore patterns, the parse will now strip the `./` prefix from the input string, and prepend the pattern with a `**` group if the input string doesn't start with an absolute filesystem path. For the Language Server, the logic converting URIs into `RomePath` will now try to strip the path to the root of the workspace from the path of the file, which has the effect of making most paths relative much like they generally are on the CLI.

## Test Plan

I've update the tests for the file ignores on the CLI to check that various forms of ignore patterns are all working correctly. I also modified the LSP tests to ensure it only constructs URIs that can be turned into valid paths for the underlying OS.

### CODE REVIEW

File: crates/rome_service/src/matcher/pattern.rs [hunk 1]
```diff
@@ -122,6 +122,27 @@ impl Pattern {
...
+            let mut is_absolute = chars.first().map_or(false, |c| path::is_separator(*c));
+
+            // On windows a pattern may also be absolute if it starts with a drive letter, a colon and a separator
+            if cfg!(windows) && !is_absolute {
+                is_absolute = matches!(chars.get(..3), Some(['a'..='z' | 'A'..='Z', ':', sep]) if path::is_separator(*sep));
+            }
+
+            // If a pattern is not absolute, insert a "**" sequence in front
+            if !is_absolute {
+                tokens.push(AnyRecursiveSequence);
```
Comment (MichaReiser) [inline crates/rome_service/src/matcher/pattern.rs:142]: What about patterns that already start with a `*`:

* `*.js` 
* `**/*.js` 

Are these handled correctly (is `***.js` a valid pattern?)

Comment (leops) [reply crates/rome_service/src/matcher/pattern.rs:142]: These patterns are handled correctly since the new logic only modifies the internal representation of the pattern and not its string representation, so while I don't think `***.js` is a valid pattern this works because it only prepending an "any sequence" in front of the pattern (for the case of `*.js` this fix also applie to this pattern and makes it work as expected, without it the pattern would match `test.js` but not `src/test.js` for instance which is probably not what the user wants)

File: crates/rome_lsp/src/session.rs [hunk 2]
```diff
@@ -127,17 +128,33 @@ impl Session {
         self.url_interner.write().unwrap().intern(url)
     }
 
-    pub(crate) fn file_path(&self, url: &lsp_types::Url) -> RomePath {
+    pub(crate) fn file_path(&self, url: &lsp_types::Url) -> Result<RomePath> {
         let file_id = self.file_id(url.clone());
-        RomePath::new(url.path(), file_id)
+        let mut path_to_file = url
+            .to_file_path()
+            .map_err(|()| anyhow!("failed to convert {url} to a filesystem path"))?;
```
Comment (ematipico) [inline crates/rome_lsp/src/session.rs:135]: What does this macro do?

File: crates/rome_lsp/tests/server.rs [hunk 3]
```diff
@@ -43,12 +43,21 @@ use tower_lsp::lsp_types::TextDocumentContentChangeEvent;
 use tower_lsp::lsp_types::TextDocumentIdentifier;
 use tower_lsp::lsp_types::TextDocumentItem;
 use tower_lsp::lsp_types::TextEdit;
-use tower_lsp::lsp_types::Url;
 use tower_lsp::lsp_types::VersionedTextDocumentIdentifier;
 use tower_lsp::lsp_types::WorkDoneProgressParams;
 use tower_lsp::LspService;
 use tower_lsp::{jsonrpc::Request, lsp_types::InitializeParams};
 
+macro_rules! url {
```
Comment (ematipico) [inline crates/rome_lsp/tests/server.rs:51]: `parse_url`? Also, could we document the macro, please? I feel there's some important information about that "workspace" and windows. I can't understand what macro is doing...

File: crates/rome_service/src/matcher/pattern.rs [hunk 4]
```diff
@@ -122,6 +122,27 @@ impl Pattern {
...
+        let is_relative = matches!(chars.get(..2), Some(['.', sep]) if path::is_separator(*sep));
+        if is_relative {
+            // If a pattern starts with a relative prefix, strip it from the pattern and replace it with "**"
+            i += 2;
+            tokens.push(AnyRecursiveSequence);
+        } else {
+            // A pattern is absolute if it starts with a path separator
+            let mut is_absolute = chars.first().map_or(false, |c| path::is_separator(*c));
+
+            // On windows a pattern may also be absolute if it starts with a drive letter, a colon and a separator
```
Comment (ematipico) [inline crates/rome_service/src/matcher/pattern.rs:135]: Could you add an example to the comment, please? I used to use windows, but I don't remember anything anymore...

File: crates/rome_service/src/matcher/pattern.rs [hunk 5]
```diff
@@ -122,6 +122,27 @@ impl Pattern {
         let mut is_recursive = false;
         let mut i = 0;
 
+        // A pattern is relative if it starts with "." followed by a separator
+        let is_relative = matches!(chars.get(..2), Some(['.', sep]) if path::is_separator(*sep));
```
Comment (ematipico) [inline crates/rome_service/src/matcher/pattern.rs:126]: Could we add some new tests in the testing suite to ensure we cover this new logic, please?

File: crates/rome_lsp/tests/server.rs (hunk 3 above)
Comment (leops) [reply crates/rome_lsp/tests/server.rs:55]: I preferred to call the macro `url` instead of `new_url` as it is used many times in the tests, and I wanted it to have a short unobtrusive name (like `vec!` from the standard library, or `T!` from out syntax crates)

**Review by ematipico — APPROVED** [review]

File: crates/rome_service/src/matcher/pattern.rs [hunk 6]
```diff
@@ -122,6 +122,30 @@ impl Pattern {
         let mut is_recursive = false;
         let mut i = 0;
 
+        // A pattern is relative if it starts with "." followed by a separator,
+        // eg. "./test" or ".\test"
+        let is_relative = matches!(chars.get(..2), Some(['.', sep]) if path::is_separator(*sep));
```
Comment (MichaReiser) [inline crates/rome_service/src/matcher/pattern.rs:127]: TIL: Yu can write `if` conditions with `matches`

File: crates/rome_service/src/matcher/pattern.rs [hunk 7]
```diff
@@ -835,4 +859,40 @@ mod test {
...
+            assert!(Pattern::new(".\\b")
+                .unwrap()
+                .matches_path(Path::new("a\\b")));
+            assert!(Pattern::new("b").unwrap().matches_path(Path::new("a\\b")));
+        }
+    }
+
+    #[test]
+    fn test_pattern_absolute() {
+        assert!(Pattern::new("/a/b")
```
Comment (MichaReiser) [inline crates/rome_service/src/matcher/pattern.rs:878]: Can we add tests for the `*.js` and `**.js` patterns

**Review by MichaReiser — APPROVED** [review]
