### PR TITLE
fix(rome_js_analyzer): escape dollar signs and backticks properly for useTemplate rule

### LINKED ISSUE #3451: 🐛 useTemplate: Handle Escape Sequence
### Environment information

```bash
Rome CLI v0.10.1-next
```

### What happened?

Run `rome check --apply-suggested` on a file containing 

```javascript
return "${aws_api_gateway_rest_api." + this.getGatewayKey() + ".id}";
```

Rome changes the expression to a template literal but without escaping `${`. 

```javascript
return `${aws_api_gateway_rest_api.${this.getGatewayKey()}.id}`;
```

Which isn't valid syntax. 

### Expected result

Rome to either not promote the use of template literals for literals containing `${` or to properly escape `${`

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by nissy-dev**
## Summary

Closes #3451 Escaped `${` properly for useTemplate rule.

## Test Plan

I add two test cases and confirmed properly escaped `${`.

### CODE REVIEW

File: crates/rome_js_analyze/src/analyzers/correctness/use_template.rs [hunk 1]
```diff
@@ -336,3 +336,16 @@ fn collect_binary_add_expression(node: &JsBinaryExpression) -> Option<Vec<JsAnyE
     };
     Some(result)
 }
+
+/// Escape dollar sign in raw string.
+fn escape_dollar_sign(unescaped_string: &str) -> String {
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/analyzers/correctness/use_template.rs:341]: Nit: It would be nice if the function returns a `Cow` to avoid the extra allocation if the string doesn't contain any `${` (which is the case for the majority of strings).

File: crates/rome_js_analyze/src/analyzers/correctness/use_template.rs [hunk 2]
```diff
@@ -336,3 +336,16 @@ fn collect_binary_add_expression(node: &JsBinaryExpression) -> Option<Vec<JsAnyE
...
+    let mut chars = unescaped_string.chars().collect::<Vec<_>>();
+    for (i, _) in unescaped_string.match_indices("${") {
+        if i == 0 {
+            chars.insert(0, '\\');
+        } else if chars[i - 1] != '\\' {
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/analyzers/correctness/use_template.rs:346]: Nice that you thought of that edge case! 

There is one more edge case. It is still necessary to add the `\` if the input is `"\\${"` where the first backslash escapes the second. 

This should be converted to `\\\${` where the third `\` escapes the `${`

**Review by MichaReiser — CHANGES_REQUESTED** [review]

File: crates/rome_js_analyze/src/analyzers/correctness/use_template.rs (hunk 2 above)
Comment (MichaReiser) [reply crates/rome_js_analyze/src/analyzers/correctness/use_template.rs:346]: Good point. An alternative would be to not error on strings that contain backticks because it having a template literal with many escapes may as well be less readable than using `+` (which we probably can also say is true if the string contains any `${` 

It should be possible to implement this functionality without using the regex crate as it is only necessary to test for the presence of specific characters. We do something similar in `normalize_newlines` where we match on a set of characters and then push the result to a new string. The code doesn't allocate for the cases where the input string contains no new lines because an empty string doesn't allocate in Rust.

https://github.com/rome/tools/blob/293552643e5242282849ee6320f5e8156a1ae75e/crates/rome_formatter/src/format_element.rs#L176-L200

Comment (xunilrj) [reply crates/rome_js_analyze/src/analyzers/correctness/use_template.rs:346]: I did a quick test here on a possible generic implementation. I have not spent to much time testing.

We can move this to a util folder and create an extension method for strings.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=22da992e7b8c070cf54f508114e437ea  

````rust
fn escape<'a>(unescaped_string: &'a str, needs_escaping: &[&str], escaping_char: char) -> std::borrow::Cow<'a, str> {
    let mut  escaped = String::new();
    let mut iter = unescaped_string.char_indices();
    'unescaped: while let Some((idx, chr)) = iter.next() {
       'candidates: for candidate in needs_escaping {
            if unescaped_string[idx..].starts_with(candidate) {
                if escaped.is_empty() {
                    escaped.push_str(&unescaped_string[0..idx]);
                }
                escaped.push(escaping_char);
                escaped.push_str(candidate);
                for _ in candidate.chars().skip(1) {
                    let _ = iter.next();
                }
                continue 'unescaped;
            }
        }
        if !escaped.is_empty() {
            escaped.push(chr);
        }
   }
   
   if escaped.is_empty() {
       std::borrow::Cow::Borrowed(unescaped_string)
   } else {
       std::borrow::Cow::Owned(escaped)
   }
}
````

**Comment by nissy-dev** [comment]
@xunilrj @MichaReiser Thanks you for your reviews and sorry for my late response! I refered to your comments  and reimplemented escape method. I would like you to review again.

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+
+        'candidates: for candidate in needs_escaping {
+            if escape_count % 2 != 0
+                && unescaped_string[idx + escaping_char_len..].starts_with(candidate)
+            {
+                for _ in candidate.chars() {
+                    let _ = iter.next();
+                }
+                escape_count = 0;
+                continue 'candidates;
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:23]: What's the reason why it is necessary to `continue` with `candiates` here. My understanding is that we've e.g. found a `\${` and skipped it. Shouldn't we now read the next character from the input string?

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+            escape_count += 1;
+        }
+
+        'candidates: for candidate in needs_escaping {
+            if escape_count % 2 != 0
+                && unescaped_string[idx + escaping_char_len..].starts_with(candidate)
+            {
+                for _ in candidate.chars() {
+                    let _ = iter.next();
+                }
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:21]: Can we use `iter.skip(candiate.len_utf8)` instead?

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 5]
```diff
@@ -0,0 +1,85 @@
+pub fn escape<'a>(
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:1]: Would you mind adding some documentation explaining what this function does? 

Ideally, with a doc test

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+    escaping_char: char,
+) -> std::borrow::Cow<'a, str> {
+    let mut escaped = String::new();
+    let escaping_char_len = escaping_char.len_utf8();
+    let mut iter = unescaped_string.char_indices();
+    let mut escape_count = 0;
+    'unescaped: while let Some((idx, chr)) = iter.next() {
+        if chr == escaping_char {
+            escape_count += 1;
+        }
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:13]: The `escape_count` can be simplified to a `bool` because all we need to know is if we have seen an escape character before. 

```suggestion
        if chr == escaping_char {
           is_escaped = !is_escaped;
        }
```


I think it should even allow to simplify the `escape_count % 2 != 0`  by doing

```rust
  if chr == escaping_char {
	is_escaped = !is_escaped;
	continue;
  }

  for candidate in needs_escaping {
    if unescaped_string[idex..].starts_with(candidate) {
    	if !is_escaped {
			if escaped.is_empty() {
				...
			}
			...
		} else {
		}
    }
  }
```

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+            }
+
+            if unescaped_string[idx..].starts_with(candidate) {
+                if escaped.is_empty() {
+                    escaped = String::with_capacity(unescaped_string.len() * 2);
+                    escaped.push_str(&unescaped_string[0..idx]);
+                }
+                escaped.push(escaping_char);
+                escaped.push_str(candidate);
+                for _ in candidate.chars().skip(1) {
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:33]: Why is it necessary to skip `1` character here?

**Review by MichaReiser — APPROVED** [review]
This is looking good to me and we can get this merged after adding some documentation to `escape` and potential simplification of the `escape` implementation

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 6 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs:13]: I thought that we need to know how many escape character is there before characters needs escaping. If there are an odd number of escape characters, a new escape is necessary, but if there are an even number of escape characters, there is no need to add an escape character.

ex)

unescaped: `\${}`     escaped: `\${}`     → no need
unescaped: `\\${}`.   escaped: `\\\${}`.  → need to add `\`
unescaped: `\\\${}`.  escaped: `\\\${}`.  → no need

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 4 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs:21]: `candidate` is String, not char. I seem it is difficult.

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 6 above)
Comment (MichaReiser) [reply crates/rome_js_analyze/src/utils/escape.rs:13]: I don't think we need the count (as `count % 2` shows). What we need to know is if it is escaped or not. 

* `\\\${` -> has one escaped `\` and one escaped `${` It's not that the escape count is 3 (to my understanding).

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 5 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs:1]: I'll add tomorrow!

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 6 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs]: I understand 👍 I refactored and simplified the logic.

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 3 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs]: I refactored and removed this logic.

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+        for candidate in needs_escaping {
+            if unescaped_string[idx..].starts_with(candidate) {
+                if !is_escaped {
+                    if escaped.is_empty() {
+                        escaped = String::with_capacity(unescaped_string.len() * 2);
+                        escaped.push_str(&unescaped_string[0..idx]);
+                    }
+                    escaped.push(escaping_char);
+                    escaped.push_str(candidate);
+                    for _ in candidate.chars().skip(1) {
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:24]: What's the reason that it is necessary to skip 1 in this loop?

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+    }
+}
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+
+    #[test]
+    fn ok_escape_dollar_signs_and_backticks() {
+        assert_eq!(escape("abc", &["${"], '\\'), "abc");
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:52]: Can we add a test for an invalid string: `escape(r#"abc\", ...)` I don't think the current implementation handles this correctly

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 10]
```diff
@@ -0,0 +1,80 @@
...
+    unescaped_string: &'a str,
+    needs_escaping: &[&str],
+    escaping_char: char,
+) -> std::borrow::Cow<'a, str> {
+    let mut escaped = String::new();
+    let mut iter = unescaped_string.char_indices();
+    let mut is_escaped = false;
+    'unescaped: while let Some((idx, chr)) = iter.next() {
+        if chr == escaping_char {
+            is_escaped = !is_escaped;
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:11]: I think we need to push the `escaping_char` here to make sure that we don't drop a final `\` (which is illegal, but something our parser might produce.


```suggestion
            is_escaped = !is_escaped;
            
	        if !escaped.is_empty() {
	            escaped.push(chr);
	        }
```

Or you change it to 

```
if char == escaping_char {
	is_escaped = !is_escaped
} else {
    for candidate in needs_escaping {
	...
}

if !escaped.is_empty() {
	escaped.push(char)
}
```

File: crates/rome_js_analyze/src/utils/escape.rs [hunk 11]
```diff
@@ -0,0 +1,80 @@
...
+                    }
+                    escaped.push(escaping_char);
+                    escaped.push_str(candidate);
+                    for _ in candidate.chars().skip(1) {
+                        iter.next();
+                    }
+                    continue 'unescaped;
+                } else {
+                    is_escaped = !is_escaped;
+                }
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/utils/escape.rs:30]: I think we can simplify this to `is_escaped = false`.

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 8 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs:24]: When the condition `if unescaped_string[idx..].starts_with(candidate)` pass, the `idx` indicates the first character of `candidate`.  It means the first character of `candidate` has already iterated.  Therefore we need to skip the rest of `candidate` except the first character.

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 11 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs]: I fixed!

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 10 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs:39]: I fixed!

File: crates/rome_js_analyze/src/utils/escape.rs (hunk 9 above)
Comment (nissy-dev) [reply crates/rome_js_analyze/src/utils/escape.rs:79]: I add a test case!
