### PR TITLE
fix(rome_js_formatter): Put closing curly on new line for empty blocks.

### LINKED ISSUE #2406: Put closing curly on new line for empty blocks.
Rome's formatter collapses empty block statements on a single line whereas Prettier enforces a line break before the closing `}` for the following statements. 

* `for..in` 
* `for..of` 
* `with` 
* `switch` 
* `switch case`

[Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#LwAvACAATABpAG4AZQAgAGIAcgBlAGEAawAgAGIAZQBmAG8AcgBlACAAYwBsAG8AcwBpAG4AZwAgAGAAfQBgAAoAaQBmACAAKAB0AHIAdQBlACkAIAB7AH0ACgBpAGYAIAAoAHQAcgB1AGUAKQAgAHsAfQAgAGUAbABzAGUAIAB7AH0ACgAKAGYAbwByACAAKAB4ACAAaQBuACAAWwBdACkAIAB7AH0ACgBmAG8AcgAgACgAeAAgAG8AZgAgAFsAXQApACAAewB9AAoACgB3AGkAdABoACgAewB9ACkAIAB7AH0ACgAKAAoAcwB3AGkAdABjAGgAIAAoACIAdABlAHMAdAAiACkAIAB7AAoAfQAKAAoAcwB3AGkAdABjAGgAIAAoACIAdABlAHMAdAAiACkAIAB7AAoAIAAgAGMAYQBzAGUAIAAiAHQAZQBzAHQAIgA6ACAAewB9AAoAfQAKAAoAdABlAHMAdAA6ACAAewB9AAoACgB0AHIAeQAgAHsACgB9ACAAYwBhAHQAYwBoACAAewAKAH0AIABmAGkAbgBhAGwAbAB5ACAAewAKAH0ACgAKAC8ALwAgAE4AbwAgAEwAaQBuAGUAIABiAHIAZQBhAGsAcwAKAGMAbABhAHMAcwAgAFQAZQBzAHQAIAB7AH0ACgBpAG4AdABlAHIAZgBhAGMAZQAgAFgAIAB7AH0ACgB0AHkAcABlACAAWAAgAD0AIAB7AH0AOwAKAAoAZgB1AG4AYwB0AGkAbwBuACAAdABlAHMAdAAoACkAIAB7AH0ACgAKAGYAbwByACAAKAA7ADsAKQAgAHsAfQAKAHcAaABpAGwAZQAgACgAdAByAHUAZQApACAAewB9AAoAZABvACAAewB9ACAAdwBoAGkAbABlACAAKAB0AHIAdQBlACkAOwAKAA==)

## Input 

```ts
// Line break before closing `}`
if (true) {}
if (true) {} else {}

for (x in []) {}
for (x of []) {}

with({}) {}


switch ("test") {
}

switch ("test") {
  case "test": {}
}

test: {}

try {
} catch {
} finally {
}

// No Line breaks
class Test {}
interface X {}
type X = {};

function test() {}

for (;;) {}
while (true) {}
do {} while (true);
```

## Prettier

```ts
// Line break before closing `}`
if (true) {
}
if (true) {
} else {
}

for (x in []) {
}
for (x of []) {
}

with ({}) {
}

switch ("test") {
}

switch ("test") {
	case "test": {
	}
}

test: {
}

try {
} catch {
} finally {
}

// No Line breaks
class Test {}
interface X {}
type X = {};

function test() {}

for (;;) {}
while (true) {}
do {} while (true);
```

## Rome

```ts
// Line break before closing `}`
if (true) {
}
if (true) {
} else {
}

for (x in []) {}
for (x of []) {}

with({}) {}

switch ("test") {}

switch ("test") {
	case "test":
		{}
}

test: {}

try {} catch {} finally {}

// No Line breaks
class Test {}
interface X {}
type X = {};

function test() {}

for (;;) {}
while (true) {}
do {} while (true);

```

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
Fix #2406 

## Test Plan
The changed snapshot testing result should match prettier

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
!bench_formatter

File: crates/rome_js_formatter/tests/specs/js/script/with.js [hunk 1]
```diff
@@ -3,3 +3,5 @@ with (   b)
 {
 	5
 }
+
+with({}) {}
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/js/script/with.js:7]: with stmt is only available when the source type is `script`, so I separate it in script dir.

File: crates/rome_js_formatter/tests/specs/ts/statement/empty_block.ts [hunk 2]
```diff
@@ -0,0 +1,2 @@
+interface X {}
+type X = {};
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/ts/statement/empty_block.ts:2]: typescript empty blocks I create a new file here,

File: crates/rome_js_formatter/tests/specs/js/module/statement/empty_blocks.js [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+}
+
+// No Line breaks
+class Test {}
+
+function test() {}
+
+for (;;) {}
+while (true) {}
+do {} while (true);
```
Comment (IWANABETHATGUY) [inline crates/rome_js_formatter/tests/specs/js/module/statement/empty_blocks.js:30]: Most empty blocks case i create a new test file here

File: crates/rome_js_formatter/tests/specs/prettier/js/switch/switch.js.snap [hunk 4]
```diff
@@ -80,11 +81,15 @@ switch (
 
 switch (
```
Comment (mrkldshv) [inline crates/rome_js_formatter/tests/specs/prettier/js/switch/switch.js.snap:82]: According to prettier formatting these statements shouldn't have empty lines inserted. https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnA7gSxmAFgAgAoASANzgCcBPAGWgHMBBKAEwDVKqOKAjCVOGwCGFTEJ4AbOADkhAWzj4AZEvzEhUCDFyVutBs3adufAcNHipshQEp8wADpQAvk4zY8RYhIYAhAK4wAMoSmPS4MBJUQbgQFPAU5mKSMvKKKmoaWjoUIWERUTFxCUmWqbb2Ts4gADQgEAAOMJjQqMigIhQQ6AAKIghtKEIS6EJUbXU8FEJgANZwwWk0mFBwyABmwwKT03MLQQ0zK-TIMBT+cHVwcjxwLCx3NBr0-kL0cABicXJCMM1QJyGgQgtRAETkEgA6rhsHBUIcwHAggNsJhSNgqMhwKgJiAVgJ4j1pvQfhstpcQAArVAADyCxykAEV-Fo1khNhJtiBDhQCVieOI4BJQQ1RLBIZgWNpkAAOAAMdVF-DgkOmDSxorhlHIoIAjiz4ETGoMQEJUABaVZ3O6gihwfWYO1Et6k9nkuoCOSYU7nCmoBlwZmssmcikwcQSqW4ZAAJjqZyEmFCAIAwhA5K6QHCAKyg-wCAAq4kGHK5pAuAElWAhgmBRE1DEEYFQpCGBM5nEA

Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/tests/specs/prettier/js/switch/switch.js.snap:82]: This pull request only resolve curly brace, empty block statement issue . If you are interested in `parentheses` formatting issue, you  make another pull request to fix it.

Comment (MichaReiser) [reply crates/rome_js_formatter/tests/specs/prettier/js/switch/switch.js.snap:82]: I don't think that what @mrkldshv mentioned is about parentheses. If you compare Rome's and Prettier's output after your change:

**Prettier**

```
switch (
  $veryLongAndVeryVerboseVariableName &&
  $anotherVeryLongAndVeryVerboseVariableName
) {
}
```

**Rome**

```
switch (
  $veryLongAndVeryVerboseVariableName && $anotherVeryLongAndVeryVerboseVariableName
) {

}
```

Then Rome seems to print an empty line between the `{` and `}` and Prettier doesn't.

Comment (mrkldshv) [reply crates/rome_js_formatter/tests/specs/prettier/js/switch/switch.js.snap:82]: Yeah, sorry if it wasn't clear. I meant empty line between the braces.

Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/tests/specs/prettier/js/switch/switch.js.snap:82]: It is my fault, thanks for pointing out.

File: crates/rome_js_formatter/src/js/statements/switch_statement.rs [hunk 5]
```diff
@@ -19,6 +19,7 @@ impl FormatNode for JsSwitchStatement {
             r_curly_token,
         } = self.as_fields();
 
+        let is_cases_empty = cases.clone().into_iter().len() == 0;
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/js/statements/switch_statement.rs:22]: Does `cases.len()` or even `cases.is_empty()` work here?

File: crates/rome_js_formatter/src/js/statements/switch_statement.rs [hunk 6]
```diff
@@ -30,13 +31,17 @@ impl FormatNode for JsSwitchStatement {
...
-                ),
+                if is_cases_empty {
+                    hard_line_break()
+                } else {
+                    join_elements_hard_line(
+                        cases
+                            .clone()
+                            .into_iter()
+                            .map(|node| node.syntax().clone())
+                            .zip(formatter.format_all(cases)?),
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/js/statements/switch_statement.rs:42]: Can you try 

```rust
cases
                        .iter()
                        .map(|node| node.syntax().clone())
                        .zip(formatter.format_all(cases)?)
```

to avoid cloning the whole list?

**Review by MichaReiser — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
@MichaReiser Fixed it.

**Comment by IWANABETHATGUY** [comment]
!bench_formatter

**Comment by MichaReiser** [comment]
Thanks @IWANABETHATGUY ! Nice work
