### PR TITLE
fix(compiler): suppression for jsx comments

### LINKED ISSUE #1546: 🐛 JSX comment suppression not working
## Steps To Reproduce

Given the following code:

```jsx

<div>
	{/** rome-ignore lint/react/noChildrenProp: this is intentional **/}
	<MyComponent children={'foo'}>
	</MyComponent>
</div>
```

Running the command `rome check` throws a lint diagnostic.

```
 test.tsx:7:7 lint/react/noChildrenProp 

  ✖ Avoid passing children using a prop.

    5 │   return <div>
    6 │     {/** rome-ignore lint/react/noChildrenProp: this is intentional **/}
  > 7 │     <Cmp children={"foo"} text="something">
      │          ^^^^^^^^^^^^^^^^
    8 │     </Cmp>
    9 │   </div>;

```

## Expected Results

The lint diagnostic should be displayed because there's a suppression comment.

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Fixes #1546 

The only way I found to fix the issue is by scanning the children of the parent, starting from the node that contains the actual comment.

## Test Plan

Created a new test

### CODE REVIEW

File: internal/compiler/suppressions.ts [hunk 1]
```diff
@@ -63,21 +63,72 @@ export function createSuppressionsVisitor(): AnyVisitor {
...
+							for (const child of path.parent.children) {
+								if (
+									child.loc?.start === node.loc?.start &&
+									child.loc?.end === node.loc?.end
+								) {
+									currentNodeFound = true;
+									continue;
+								}
+								// here we don't check text because our parser tracks newlines and tabs/spaces as text
+								if (currentNodeFound && child.type !== "JSXText") {
```
Comment (jamiebuilds) [inline internal/compiler/suppressions.ts:91]: Should this only check whitespace-only text nodes?

Comment (ematipico) [reply internal/compiler/suppressions.ts:91]: They are `JSXText`. That's the relative AST node we get 

```
JSXExpressionContainer {
	expression: JSXEmptyExpression {innerComments: ["1"], trailingComments: []}
}
JSXText {value: "\n\t\t"}
JSXElement {
	name: JSXReferenceIdentifier {name: "Cmp"}
}

```
