### PR TITLE
test(xtask): Enable all test262 tests for parser coverage

### LINKED ISSUE #1891: 📎 Enable all test262 tests for parser coverage
### Description

@xunilrj pointed out in [discord](https://discord.com/channels/678763474494423051/678763474930761739/922602033406685204) that our coverage runs only 17608 tests (out of 40000+). 

We can make it cover more by filtering out [negative tests](https://github.com/tc39/test262/blob/main/INTERPRETING.md#negative) instead of the ones that [do not have a feature](https://github.com/rome/tools/blob/main/xtask/src/coverage/files.rs#L131)
> If a test configured with the negative attribute completes without throwing an exception, or if the name of the thrown exception's constructor does not match the specified constructor name, or if the error occurs at a phase that differs from the indicated phase, the test must be interpreted as "failing."

Changing to `.filter(|file| file.meta.negative.is_none())` gives us
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   40790   │ 40237  │  535   │   18   │  98.64   │
└───────────┴────────┴────────┴────────┴──────────┘
```

We can also add negative tests `.filter(|file| file.meta.negative.is_some())`, where it gives us 
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   4218    │  2531  │  1651  │   36   │  60.00   │
└───────────┴────────┴────────┴────────┴──────────┘
```

Note1: we need to filter out module tests
>  Test262 includes tests for ECMAScript 2015 module code, denoted by the "module" metadata flag. Files bearing a name which includes the sequence _FIXTURE MUST NOT be interpreted as standalone tests; they are intended to be referenced by test files.

Note2: our coverage tests run super slow at the moment, which should be looked into.

### PR DESCRIPTION
**Pull request by Boshen**
closes #1891

## Summary
It's safe to enable all test262 tests, we aim to pass them all 🏆 

## Test Plan
```
cargo run -p xtask --release -- coverage
```

### CODE REVIEW

**Comment by Boshen** [comment]
```
Run comment="$(cargo xtask compare ./base_results.json ./new_results.json  --markdown)"
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/xtask compare ./base_results.json ./new_results.json --markdown`
```

The tests are running forever because of dev mode 😞

**Comment by Boshen** [comment]
No bot comment because output is too large
> Error: The template is not valid. .github/workflows/test262.yml (Line: 112, Col: 17): The maximum allowed memory size was exceeded while evaluating the following expression: format('### Test262 comparison coverage results on {0}

File: xtask/src/coverage/files.rs [hunk 1]
```diff
@@ -128,7 +128,7 @@ pub fn get_test_files(query: Option<&str>, pool: &Pool, json: bool) -> Vec<TestF
 					let code = read_to_string(entry.path()).ok()?;
 					let meta = read_metadata(&code).ok()?;
 					let path = entry.into_path();
-					Some(TestFile { meta, code, path }).filter(|file| file.meta.features.is_empty())
```
Comment (MichaReiser) [inline xtask/src/coverage/files.rs:131]: Can we exclude any negative tests that aren't raising parse errors? Is there a way to filter out any tests that only validate runtime correctness?

**Comment by Boshen** [comment]
All tests
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   45008   │ 42768  │  2186  │   54   │  95.02   │
└───────────┴────────┴────────┴────────┴──────────┘
```

negative tests with parse phase only
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   44951   │ 42717  │  2180  │   54   │  95.03   │
└───────────┴────────┴────────┴────────┴──────────┘
```

File: xtask/src/coverage/files.rs (hunk 1 above)
Comment (Boshen) [reply xtask/src/coverage/files.rs:131]: Done, the existing code has all the relevant context to work with, which is super nice.

**Comment by MichaReiser** [comment]
Thanks for filtering out the non-parse negative tests and sorry for the late review. We all enjoyed a few days off over Christmas and new year. Happy new year and thanks for this contribution.
