### PR TITLE
fix(rome_js_analyze): #4348

### LINKED ISSUE #4348: 🐛 rule `style/noNonNullAssertions` emit incorrect code action
### Environment information

```block
Rome v12
```

### What happened?

The rule `style/noNonNullAssertions` emits an incorrect code action. In particular, its AST is wrong!

Given this code:

```js
session!.hey
```
It seems to return a correct code:
```js
session?.hey
```

Although, the AST is wrong:

```
CommitChange {
            parent_depth: 11,
            parent: Some(
                0: TS_NON_NULL_ASSERTION_EXPRESSION@23..31
                  0: JS_IDENTIFIER_EXPRESSION@23..30
                    0: JS_REFERENCE_IDENTIFIER@23..30
                      0: IDENT@23..30 "session" [] []
                  1: BANG@30..31 "!" [] []
                ,
            ),
            parent_range: Some(
                (
                    23,
                    31,
                ),
            ),
            new_node_slot: 1,
            new_node: Some(
                Token(
                    QUESTION@0..1 "?" [] [],
                ),
            ),
        },
```

Which is wrong and it results in an endless loop when calling `rome check --apply-unsafe` because there's always a `TS_NON_NULL_ASSERTION_EXPRESSION`.

The correct way is to return a new code, which is a `JsStaticMemberExpression`. [Playground](https://docs.rome.tools/playground/?quoteStyle=single&trailingComma=none&indentWidth=4&code=cwBlAHMAcwBpAG8AbgA%2FAC4AcwBvAG0AZQB0AGgAaQBuAGcA)

### Expected result

The rule to emit a correct AST and not result in an endless loop when calling `rome check --apply-unsafe`

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #4348.

I also added some comments and made minor refactoring.

## Test Plan

No change.

## Changelog

- [x] The PR requires a changelog line

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

File: crates/rome_js_analyze/tests/specs/style/noNonNullAssertion/valid.ts.snap [hunk 1]
```diff
@@ -1,5 +1,6 @@
 ---
 source: crates/rome_js_analyze/tests/spec_tests.rs
+assertion_line: 96
```
Comment (ematipico) [inline crates/rome_js_analyze/tests/specs/style/noNonNullAssertion/valid.ts.snap:3]: I believe we can revert the changes in this file

**Review by ematipico — APPROVED** [review]
