### PR TITLE
fix(rome_js_analyze): fix noShoutyConstants with empty string

### LINKED ISSUE #3867: 🐛 false positive for noShoutyConstants on empty strings
### Environment information

According https://rome.tools/docs/lint/rules/noShoutyConstants/

> Disallow the use of constants which its value is the upper-case version of its name.

Such code snippet should not emit a warning:

```javascript
const A = ""
```

https://docs.rome.tools/playground/?code=YwBvAG4AcwB0ACAAQQAgAD0AIAAiACIACgBjAG8AbgBzAHQAIABCACAAPQAgAEEA&typescript=false&jsx=false

If it's alright, I'd like to take this issue on and open a PR.

### What happened?

Rome emitted a diagnostic.

### Expected result

This code snippet will not raise an error.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by rosslh**
## Summary

Closes #3867

## Test Plan

> cargo test -p rome_js_analyze -- shouty

With some new test cases which were missing:

```javascript
const Empty = "";
export const E = Empty;

const NotMatching = "DoesNotMatch";
export const F = NotMatching;

const matchingLowercase = "matchingLowercase";
export const G = matchingLowercase;

const AL = "ALPHA";
export const H = AL;

const ALPHA = "AL";
export const I = ALPHA;
```

### CODE REVIEW

File: crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs [hunk 1]
```diff
@@ -66,6 +66,10 @@ fn is_id_and_string_literal_inner_text_equal(
         .as_js_string_literal_expression()?;
     let literal_text = literal.inner_string_text().ok()?;
 
+	if literal_text == "" {
+		return None;
+	}
+
     for (from_id, from_literal) in id_text.chars().zip(literal_text.chars()) {
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs:73]: The problem is that `zip` returns `None` as soon as one of the iterator ends. So the lint rule reports `AL = ALPHA` even though the strings are not equal. 

This can be fixed by manually iterating over the chars

```
if id_text.len() != literal_text.len() {
  return None;
}

let mut id_iter = id_text.chars();
let mut literal_iter = literal_text.chars();

loop {
  match (id_iter.next(), literal_iter.next()) {
    (Some(id_char), Some(literal_char)) => {
		if id_char != literal_char || !id_char.is_lowercase() {
           return None;
        }
	},
   (None, None) => break,
	// Same byte length but different characters
    (Some(_), None)) | (None, Some(_)) => return None,
  }
}
```

**Review by MichaReiser — CHANGES_REQUESTED** [review]

File: crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs (hunk 1 above)
Comment (rosslh) [reply crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs:73]: Good catch @MichaReiser. Correct me if I'm wrong, but I think this code should be enough to fix the problem:

```rust
if id_text.len() != literal_text.len() {
  return None;
}
```

If we make sure the strings are the same length, the `zip` code should work as expected, right?

Comment (MichaReiser) [reply crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs:73]: Yeah, I think you're right. I was worried about the case where one string uses unicode characters (that are multiple bytes) and the other does not but the chars would then be different.

File: crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs [hunk 2]
```diff
@@ -66,6 +66,10 @@ fn is_id_and_string_literal_inner_text_equal(
         .as_js_string_literal_expression()?;
     let literal_text = literal.inner_string_text().ok()?;
 
+	if id_text.len() != usize::from(literal_text.len()) {
+		return None;
+	}
+
     for (from_id, from_literal) in id_text.chars().zip(literal_text.chars()) {
         if from_id != from_literal {
             return None;
```
Comment (MichaReiser) [inline crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs:75]: Nit: We can remove one of the `is_lowercase` checks below. Either they are both lowercase or both are not.

**Review by MichaReiser — APPROVED** [review]

**Review by MichaReiser — APPROVED** [review]

**Comment by MichaReiser** [comment]
Thank you!
