### PR TITLE
fix(rslint_parser): Fix spread call expression arguments

### LINKED ISSUE #2169: 🐛 Spread elements are not allowed in call expressions
### Environment information

```bash
N/A
```

### What happened?

The expression `a(...b)` is parsed as an unknown expression with no diagnostics

### Expected result

The current grammar only allow for a list of `JsAnyExpression` in function calls arguments, I'm guessing it should have an optional JsSpread (or an entirely new node) after the expressions list

### Configuration file of your project

_No response_

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

Call expressions can contain any number of spread arguments:

```
let a, b, c, d;
function test(...args) { console.log(args); }

test(...a, ...b, c, ...d);
```

The parser already parse these correctly but the grammar didn't allow `JsSpread` nodes in the argument position.

This PR introduces a new `JsAnyCallArgument` that is either a `JsAnyExpression` or a `JsSpread`.

Fixes #2169

## Test Plan

Added new parser tests

### CODE REVIEW

File: crates/rome_formatter/tests/specs/prettier/js/comments/issues.js.snap [hunk 1]
```diff
@@ -96,8 +96,7 @@ throw new ProcessSystemError(
 
 // Missing one level of indentation because of the comment
 const rootEpic = (actions, store) =>
-  (
-  combineEpics(...epics)(actions, store)// Log errors and continue.
+  (combineEpics(...epics)(actions, store)// Log errors and continue.
```
Comment (MichaReiser) [inline crates/rome_formatter/tests/specs/prettier/js/comments/issues.js.snap:99]: @leops should we ensure that there's single whitespace before comments?

**Review by ematipico — APPROVED** [review]

File: crates/rome_formatter/tests/specs/prettier/js/comments/issues.js.snap (hunk 1 above)
Comment (leops) [reply crates/rome_formatter/tests/specs/prettier/js/comments/issues.js.snap:99]: That's normally the case for comments in trailing position, but this comment was originally a leading trivia on the next token so I think what's actually missing here is a line break. I'll track this separately

**Review by leops — APPROVED** [review]
