### PR TITLE
fix(rome_cli): issue #3175

### LINKED ISSUE #3175: 🐛 `rome format` ignores command line options
### Environment information

```bash
Version: `main`
```

### What happened?

Run `rome` with `quote-style="single"` 

```bash
cargo run --bin rome --release format ~/Desktop/jquery.min.js --quote-style=single
```

Rome formats the string literals in `jquery.min.js` with double quotes.

### Expected result

The command line arguments take precedence over the configuration and Rome formats the string literals in `jquery.min.js` with single quotes 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Fixes #3175 

The issue was caused a particular shape of the `rome.json` and the old logic was not taken that into consideration. For example, when the `javascript.formatter` section was not present in the configuration file and CLI requests to override some default of that part of the configuration.

This PR should fix these cases.

## Test Plan

I added two test cases

### CODE REVIEW

File: crates/rome_cli/src/commands/format.rs [hunk 1]
```diff
@@ -13,6 +13,7 @@ pub(crate) fn format(mut session: CliSession) -> Result<(), Termination> {
     let configuration = load_config(&session.app.fs, None)?;
     let configuration = apply_format_settings_from_cli(&mut session, configuration)?;
 
+    dbg!(&configuration);
```
Comment (leops) [inline crates/rome_cli/src/commands/format.rs:16]: Debugging leftover

File: crates/rome_cli/src/commands/format.rs [hunk 2]
```diff
@@ -105,6 +106,14 @@ pub(crate) fn apply_format_settings_from_cli(
...
 
+    // if at least one argument is passed via CLI and no "formatter" configuration was passed
+    // via `rome.json`, we need to create it
+    if (line_width.is_some() | indent_style.is_some() | size.is_some())
+        && configuration.formatter.is_none()
+    {
+        configuration.formatter = Some(FormatterConfiguration::default());
+    }
+
     if let Some(formatter) = configuration.formatter.as_mut() {
```
Comment (leops) [inline crates/rome_cli/src/commands/format.rs:117]: Instead of conditionally writing on `.as_mut()` and relying on having correctly written the `formatter` field of the configuration earlier in the code it would probably be easier to do `let formatter = configuration.formatter.get_or_insert_with(FormatterConfiguration::default);` in the places where the field is being written to

File: crates/rome_service/src/file_handlers/javascript.rs [hunk 3]
```diff
@@ -381,6 +381,7 @@ fn format(
 ) -> Result<Printed, RomeError> {
     let options = settings.format_options::<JsLanguage>(rome_path);
 
+    dbg!(&options);
```
Comment (leops) [inline crates/rome_service/src/file_handlers/javascript.rs:384]: Debugging leftover
