### PR TITLE
fix(rome_cli): do not print lint warnings for the format command

### LINKED ISSUE #2670: 🐛 `rome format` shouldn't emit lint warnings
### Environment information

```bash
Version: 0.6.0 

Command: `rome format` inside of the `website` folder
```

### What happened?

1. Change the `===` to a `==` in https://github.com/rome/tools/blob/9f624d4bee0d79a600ea28e177cf11cf5ca65b23/website/playground/src/SourceTypeSelect.tsx#L64
2. Run `cargo run -p rome_cli -- format src/` inside the `playground` folder
3. It emits

```
warning[noDoubleEquals]: Do not use the == operator
   ┌─ src/SourceTypeSelect.tsx:64:29
   │
64 │                             disabled={sourceType == SourceType.Script}
   │                                                  -- Do not use the == operator

Replace with strict equality
      | @@ -61,7 +61,7 @@
60 60 |                                                                 setIsTypeScript(e.target.checked);
61 61 |                                                         }}
62 62 |                                                         className="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded disabled:opacity-30"
63    | -                                                       disabled={sourceType == SourceType.Script}
   63 | +                                                       disabled={sourceType === SourceType.Script}
64 64 |                                                 />
65 65 |                                         </div>
66 66 |                                         <div className="ml-1 text-sm">
```

### Expected result

`rome format` only prints syntax errors but not lint warnings/errors. 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

This PR fixes #2670 by skipping the printing of diagnostics in traversal operations for the `format` commands if no errors were returned by `pull_diagnostics`
Additionally, I exposed the `categories` filter from `rome_analyze`  to consumers of the `pull_diagnostics` method to let clients chose which diagnostics categories they want: in format mode this is used to only run rules with the `SYNTAX` category and ignore `LINT` rules, to avoid emitting diagnostics that would not impact the correctness of formatting in the first place

## Test Plan
I added an additional `lint_warning` test to the CLI verifying no warnings are printed to the console when formatting files with lint errors

### CODE REVIEW

File: crates/rome_lsp/src/session.rs [hunk 1]
```diff
@@ -93,9 +94,10 @@ impl Session {
         let workspace_settings = self.config.read().get_workspace_settings();
 
         let diagnostics = if workspace_settings.analysis.enable_diagnostics {
-            let diagnostics = self
-                .workspace
-                .pull_diagnostics(PullDiagnosticsParams { path: rome_path })?;
+            let diagnostics = self.workspace.pull_diagnostics(PullDiagnosticsParams {
+                path: rome_path,
+                categories: RuleCategories::SYNTAX | RuleCategories::LINT,
+            })?;
```
Comment (MichaReiser) [inline crates/rome_lsp/src/session.rs:100]: Nit: What do you think of having a `new` function that only accepts the path and defaults the categories to all categories and a method  `with_categories` that changes the categories to the specified categories?

**Review by MichaReiser — APPROVED** [review]
