### PR TITLE
Fix markup format ranges spanning multiple lines

### LINKED ISSUE #971: 📎 Fatal error coloring sometimes has unhighlighted trailing characters
I have no idea what causes this. I think it consistently repros but haven't had a chance to look into it.

### PR DESCRIPTION
**Pull request by sebmck**
## Summary

Fixes #971. Thanks @jer3m01 for the consistent repro!

## Test Plan

Added a new test, ran `./rome ci`

### CODE REVIEW

File: internal/cli-layout/Grid.ts [hunk 1]
```diff
@@ -721,7 +721,9 @@ export default class Grid {
 			// Add middle lines
 			for (let i = ob1Get1(start.line) + 1; i < ob1Get1(end.line); i++) {
 				const line = ob1Coerce1(i);
-				this.setRange(line, ob1Coerce1(1), this.getLineWidth(line), ancestry);
+				const start = ob1Coerce1(1);
+				const end = ob1Inc(this.getLineWidth(line));
```
Comment (sebmck) [inline internal/cli-layout/Grid.ts:725]: The middle lines of a range weren't having their `end` properly set. The range ends don't include the end index.
