### PR TITLE
fix(rome_js_analyze): `noRedeclaration` declaration merging

### LINKED ISSUE #4287: 🐛 noRedeclaration reports mergeable declarations
### Environment information

```block
CLI:
  Version:              11.0.0-nightly.846c15e
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"
  JS_RUNTIME_VERSION:   "v18.12.0"
  JS_RUNTIME_NAME:      "node"
  NODE_PACKAGE_MANAGER: "npm/8.19.2"

Rome Configuration:
  Status:               Loaded successfully
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0
```

### What happened?

In _TypeSCript_, some [declarations can be merged](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

The [noredeclaration]( https://docs.rome.tools/lint/rules/noredeclaration/) does not take this into account.
The following code is thus rejected:

```ts
interface I { f(): void }
interface I { g(): void }
```

### Expected result

The rule should take declaration merging into account.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fixes #4287.

While I was fixing the issue, I realized that [noDuplicateParameters](https://docs.rome.tools/lint/rules/noduplicateparameters/) and `noRedeclaration` have some intersections. We could merge these two rules in another PR?

EDIT: this PR also allows duplicate parameters. To prevent duplicate parameters use `noSuplicateParameters` instead.

## Test Plan

Extended.

## Documentation

Updated.

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

File: crates/rome_js_syntax/src/binding_ext.rs [hunk 1]
```diff
@@ -43,6 +43,52 @@ declare_node_union! {
             | JsCatchDeclaration
 }
 
+impl AnyJsBindingDeclaration {
+    /// Is `self` and `other` mergeable delcarations?
+    /// See: https://www.typescriptlang.org/docs/handbook/declaration-merging.html
```
Comment (ematipico) [inline crates/rome_js_syntax/src/binding_ext.rs:48]: We should make this rustdoc more in line with [the rest](https://github.com/rome/tools/blob/main/crates/rome_js_syntax/src/expr_ext.rs#L21-L30): an explanation of the function and a doctest to make sure the intended API works, with an example of usage.

For example, we should explain what "mergeable" means to the first time contributor.

File: crates/rome_js_syntax/src/binding_ext.rs [hunk 2]
```diff
@@ -43,6 +43,52 @@ declare_node_union! {
...
+    pub fn is_mergeable(&self, other: &AnyJsBindingDeclaration) -> bool {
+        fn inner(a: &AnyJsBindingDeclaration, b: &AnyJsBindingDeclaration) -> bool {
```
Comment (ematipico) [inline crates/rome_js_syntax/src/binding_ext.rs:50]: Any reason why this function is here rather than outside? Or you could even crate a private function inside  `AnyJsBindingDeclaration`

**Review by ematipico — CHANGES_REQUESTED** [review]

File: crates/rome_js_syntax/src/binding_ext.rs (hunk 2 above)
Comment (Conaclos) [reply crates/rome_js_syntax/src/binding_ext.rs:50]: > Any reason why this function is here rather than outside?

Do you mean that we could move this function in the rule file?

> Or you could even crate a private function inside AnyJsBindingDeclaration

I do not understand what you mean...

Comment (ematipico) [reply crates/rome_js_syntax/src/binding_ext.rs:60]: I meant something like

```rust
impl AnyJsBindingDeclaration {
	pub fn is_mergeable(&self, other: &AnyJsBindingDeclaration) -> bool {
		AnyJsBindingDeclaration::can_merge(self, other) || 
			AnyJsBindingDeclaration::can_merge(other, self) 
	}
	// this function won't be exposed as API
	fn can_merge(&a: AnyJsBindingDeclaration, &b: &AnyJsBindingDeclaration) -> bool {}
}
```

File: crates/rome_js_syntax/src/binding_ext.rs [hunk 3]
```diff
@@ -43,6 +43,62 @@ declare_node_union! {
...
+impl AnyJsBindingDeclaration {
+    /// Returns `true` if `self` and `other` are mergeable declarations.
+    ///
+    /// ## Examples
+    ///
+    /// In the following code, the enum `Order` merges with the namespace `Order`.
+    ///
+    /// ```ts
+    /// enum Order { ... }
+    /// namespace Order { ... }
```
[the remark this answers is not in the document]
Comment (Conaclos) [reply crates/rome_js_syntax/src/binding_ext.rs:55]: Inside the code? Have you some pointers? I am not sure to understand how it is useful...

[the remark this answers is not in the document]
Comment (ematipico) [reply crates/rome_js_syntax/src/binding_ext.rs:55]: https://github.com/rome/tools/blob/main/crates/rome_js_syntax/src/jsx_ext.rs#L11-L21

This is another example. This is a doctest, the code inside code block is valid rust code, and works as test. It works as you would consuming the API, and the assertion is run by cargo when running the test suite.

This is how the Rust project writes their internal documentation and tests.

[the remark this answers is not in the document]
Comment (Conaclos) [reply crates/rome_js_syntax/src/binding_ext.rs:55]: Is there an easy way to produce an AST from a string?

File: crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs [hunk 4]
```diff
@@ -42,43 +53,40 @@ declare_rule! {
...
         version: "12.0.0",
         name: "noRedeclaration",
         recommended: true,
     }
 }
 
-type Duplicates = HashMap<String, Vec<Binding>>;
-
-type Redeclaration = (String, TextRange, Binding);
+type Redeclaration = (String, TextRange, TextRange);
```
Comment (ematipico) [inline crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs:63]: We could document what each type represents.

File: crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs [hunk 5]
```diff
@@ -20,6 +21,11 @@ declare_rule! {
     /// ```
     ///
     /// ```js,expect_diagnostic
+    /// function f() {}
+    /// function f() {}
```
Comment (ematipico) [inline crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs:25]: Could you add 
```js
let a;
let a;
```

To the list of invalid examples?

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
> While I was fixing the issue, I realized that [noDuplicateParameters](https://docs.rome.tools/lint/rules/noduplicateparameters/) and `noRedeclaration` have some intersections. We could merge these two rules in another PR?

The two rules have different scopes. `noRedeclaration` should catch cases like

```js
let a;
let a;
```
Which causes a different error (runtime).

**Comment by Conaclos** [comment]
> Which causes a different error (runtime).

Good point.
It is a bit more complex than it. The rule also forbids `var` redeclaration that are not a runtime error.
However, it is a special case.

The rule must thus be reworked to avoid to report duplicate parameters.

**Comment by Conaclos** [comment]
Note: the rule also checks for function redeclarations which are allowed in JavaScript.

File: crates/rome_js_syntax/src/binding_ext.rs [hunk 6]
```diff
@@ -43,6 +43,119 @@ declare_node_union! {
...
+    ///
+    /// assert!(!class_decl.is_mergeable(&enum_decl));
+    /// assert!(!enum_decl.is_mergeable(&class_decl));
+    /// ```
+    pub fn is_mergeable(&self, other: &AnyJsBindingDeclaration) -> bool {
+        Self::can_merge(self, other) || Self::can_merge(other, self)
+    }
+
+    /// Please use `is_mergeable`.
+    /// `can_merge` ise sensible to the order of arguments.
```
Comment (ematipico) [inline crates/rome_js_syntax/src/binding_ext.rs:106]: "is" sensible

File: crates/rome_js_syntax/src/binding_ext.rs [hunk 7]
```diff
@@ -43,6 +43,119 @@ declare_node_union! {
...
+    fn can_merge(a: &AnyJsBindingDeclaration, b: &AnyJsBindingDeclaration) -> bool {
```
Comment (ematipico) [inline crates/rome_js_syntax/src/binding_ext.rs:107]: I think this function can be declared as a `const fn`

File: crates/rome_js_syntax/src/binding_ext.rs [hunk 8]
```diff
@@ -43,6 +43,119 @@ declare_node_union! {
...
+                | AnyJsBindingDeclaration::TsInterfaceDeclaration(_)
+                | AnyJsBindingDeclaration::TsModuleDeclaration(_),
+            ) => true,
+            (_, _) => false,
+        }
+    }
+
+    /// Returns `true` if `self` is a formal parameter, a rest parameter,
+    /// a property parameter, or a bogus parameter.
+    pub fn is_parameter_like(&self) -> bool {
```
Comment (ematipico) [inline crates/rome_js_syntax/src/binding_ext.rs:148]: I think this function can declared as a `const fn`

**Review by ematipico — APPROVED** [review]
