### PR TITLE
fix(rome_fs): Fix incorrect detection of infinite symlinks

### LINKED ISSUE #4193: 🐛 Infinite symlink expansion error when there's no infinite symlink AFAICT
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...
```

### What happened?

1. running `npx rome check .`
2. It complains about a bunch of file symlinks I have

For example:
```
../tools/node/npm-runner.js internalError/fs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ Infinite symlink expansion
  
  ✖ Rome encountered a file system entry that leads to an infinite symbolic link expansion, causing an infinite cycle: ../tools/node/npm-runner.js
```

Problems:
1. I have no idea what working directory it's in because I run rome from `.` and the npm-runner.js script is located at `workflow/tools/node/npm-runner.js`
2. I have no idea what the source of the symlink is that it's having problems with
3. npm-runner.js is not a symlink:
```
$ ls -l workflow/tools/node/npm-runner.js
-rwxr-xr-x 1 vlovich vlovich 7707 Jan 24 18:20 workflow/tools/node/npm-runner.js
```

Relevant information:
An example of a symlink looks like:
```
ls -l scripts/my-tool
lrwxrwxrwx 1 vlovich vlovich 36 Jan 12 20:22 scripts/my-tool -> ../workflow/tools/node/npm-runner.js
```

`workflow` is a submodule to another project. I get the similar errors when running rome from within the submodule (or even as a standalone checkout) so most of the errors about the symlinks that exist within workflow (the npm-runner.js script is reused within workflow and within projects that import it).

### Expected result

Simple symlinks to JS files shouldn't cause infinite symlink errors.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by arendjr**
## Summary

This makes a few changes to how potentially infinite symlinks are detected in order to prevent false positives:

- It maintains the logic that if traversal discovers a file that has already been discovered, it will be skipped, but no more diagnostics will be reported in this situations. This handles the situation where symlinks between directories cause an infinite cycle, since the directories themselves will be inserted into the interner. Given that this situation causes no other issues for Rome, I think it's not a problem that these kinds of infinite cycles are not being reported by Rome anymore.
- It explicitly checks whether symlinks point at other symlinks and recursively follows them if so. While doing this, it tracks the depth and bails with a `DeeplyNestedSymlinkExpansion` diagnostic if it exceeds a maximum depth (currently set to 3).
- Given the changed nature of the detection, `DeeplyNestedSymlinkExpansion` replaces `InfiniteSymlinkExpansion` and the diagnostic messages have been updated too.

Fixes #4193, #4395.

## Test Plan

Tests are included in the PR. I also renamed some of the test folders used by tests, since running `cargo test symlink` would cause regular failures with parallel tests interfering with each other's directories.

~~There is still one issue with the tests in this PR: There's a new test case that tests two symlinks pointing at one another, but because the traversal happens in parallel the order of the diagnostics is undefined. This causes the test to be unstable currently, so I need a way to restrict this file to running on a single thread. I'm not sure how to do this with rayon, so suggestions would be welcomed.~~ **Update:** Fixed now.

### CODE REVIEW

File: crates/rome_fs/src/fs/os.rs [hunk 1]
```diff
@@ -338,6 +286,72 @@ fn handle_dir_entry<'scope>(
     }));
 }
 
+/// Handles symlinks by recursively following them (up to `MAX_SYMLINK_DEPTH`),
+/// and returning the new type of the file pointed to. Performs error reporting,
+/// so the returned error type is `()`.
+fn handle_symlink(
+    mut path: PathBuf,
+    ctx: &dyn TraversalContext,
+) -> Result<(PathBuf, FileType), ()> {
```
Comment (ematipico) [inline crates/rome_fs/src/fs/os.rs:295]: It's not logically correct returning a `Result` without an error. An error **must be handled**, but in your logic, you don't handle it. Considering the case, it's more appropriate returning an `Option`

File: crates/rome_fs/src/fs/os.rs [hunk 2]
```diff
@@ -338,6 +286,72 @@ fn handle_dir_entry<'scope>(
     }));
 }
 
+/// Handles symlinks by recursively following them (up to `MAX_SYMLINK_DEPTH`),
+/// and returning the new type of the file pointed to. Performs error reporting,
+/// so the returned error type is `()`.
```
Comment (ematipico) [inline crates/rome_fs/src/fs/os.rs:291]:
```suggestion
/// Handles symlinks by recursively following them up to [MAX_SYMLINK_DEPTH],
/// and returning the type of file pointed to. Performs error reporting,
/// so the returned error type is `()`.
```

Could you add a doc section like this:

```markdown
///  ## Returns
/// 
///  Returns a tuple where the first argument is ... and the second is ...
```

File: crates/rome_fs/src/fs/os.rs [hunk 3]
```diff
@@ -338,6 +286,72 @@ fn handle_dir_entry<'scope>(
...
+fn handle_symlink(
```
Comment (ematipico) [inline crates/rome_fs/src/fs/os.rs:292]: nit: `follow_symbolic_link`

**Review by ematipico — COMMENTED** [review]
What's the main reason we should follow the symbolic links for three levels? I think this is really important to understand and explain because we will need to document this behaviour.

File: crates/rome_fs/src/fs/os.rs (hunk 1 above)
Comment (arendjr) [reply crates/rome_fs/src/fs/os.rs:295]: Well, the intent was to communicate that there _is_ an error, you just don't need to know anything about it, since the diagnostics are already handled. I could also create a named struct without any fields if that makes it clearer?

**Comment by arendjr** [comment]
> What's the main reason we should follow the symbolic links for three levels? I think this is really important to understand and explain because we will need to document this behaviour.

Frankly, it's rather arbitrary. If the value is 1, we wouldn't support symlinks to symlinks at all. While having symlinks to symlinks is probably not common, not supporting them at all is probably not what we want either, so I picked something higher. 2 would probably be sufficient for pretty much anyone, but just in case I picked 3 :)

To be honest I'm not sure I would even try documenting this. I would judge chances that anyone runs into this because they have even deeper nesting to be negligibly small. And if they do, the message saying they have too deeply nested should be clear enough. In other words, for all practical intends and purposes, I would expect this to be not really a user-facing issue unless someone has a *really* special setup.

**Comment by ematipico** [comment]
> There is still one issue with the tests in this PR: There's a new test case that tests two symlinks pointing at one another, but because the traversal happens in parallel the order of the diagnostics is undefined. This causes the test to be unstable currently, so I need a way to restrict this file to running on a single thread. I'm not sure how to do this with rayon, so suggestions would be welcomed.

We have these cases in our test suite. We usually remove all the diagnostics messages from the console: https://github.com/rome/tools/blob/main/crates/rome_cli/tests/commands/check.rs#L1213-L1231

You could use the same trick

**Comment by arendjr** [comment]
> We have these cases in our test suite. We usually remove all the diagnostics messages from the console: https://github.com/rome/tools/blob/main/crates/rome_cli/tests/commands/check.rs#L1213-L1231

Thanks! I've used a similar trick to just check for the highlights in the output that the test would expect, instead of using a snapshot here.

The CHANGELOG entry is added too.

**Review by ematipico — APPROVED** [review]
