### PR TITLE
Resolver: Add allowPartial option to resolveEntry to force full project loading

### LINKED ISSUE #1321: 🐛 Unable to build rome (vendor/rome.cjs)
## Environment

```
Environment Variables
  Object {TERM: "xterm-256color"}

User Config
  unset

Rome Version
  10.0.4-beta-dev

Node Version
  14.7.0

Platform
  darwin x64 20.2.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 8
    columns: 265
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    silent: false
    cwd: ___R$project$rome$$internal$path$index_ts$AbsoluteFilePath: /Users/emanuele/www/rome
    realCwd: ___R$project$rome$$internal$path$index_ts$AbsoluteFilePath: /Users/emanuele/www/rome
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 28_090_368
      pid: 64_649
      uptime: 0.242247348
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 28_090_368
        ownedBytes: 0n
        ownedFileCount: 0
        pid: 64_649
        uptime: 0.242160849
      }
    ]
  }


```

## Steps To Reproduce

1. `./rome run scripts/commit-rome.ts`

```

 project-rome/@internal/core/server/fs/MemoryFileSystem.ts:640:9 internalError/request  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ /Users/emanuele/www/rome/public-packages/rome: Not found in memory file system

   1. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.getFileStatsAssert (project-rome/@internal/core/server/fs/MemoryFileSystem.ts:640:9)
   2. ___R$project$rome$$internal$core$server$WorkerManager_ts$default.getNextWorker (project-rome/@internal/core/server/WorkerManager.ts:370:20)
   3. ___R$project$rome$$internal$core$server$fs$FileAllocator_ts$default.assignOwner (project-rome/@internal/core/server/fs/FileAllocator.ts:201:18)
   4. ___R$project$rome$$internal$core$server$WorkerQueue_ts$default.pushPath (project-rome/@internal/core/server/WorkerQueue.ts:54:17)
   5. Function.maybeAllowMissing (project-rome/@internal/fs/FileNotFound.ts:39:11)
   6. ___R$project$rome$$internal$core$server$dependencies$DependencyGraph_ts$default.seed (project-rome/@internal/core/server/dependencies/DependencyGraph.ts:242:3)
   7. ___R$project$rome$$internal$core$server$bundler$BundleRequest_ts$default.stepAnalyze (project-rome/@internal/core/server/bundler/BundleRequest.ts:99:3)
   8. ___R$project$rome$$internal$core$server$bundler$BundleRequest_ts$default.bundle (project-rome/@internal/core/server/bundler/BundleRequest.ts:328:16)
   9. ___R$project$rome$$internal$core$server$bundler$Bundler_ts$default.bundle (project-rome/@internal/core/server/bundler/Bundler.ts:470:14)
  10. createBundle (project-rome/@internal/core/server/bundler/Bundler.ts:307:18)
  11. ___R$project$rome$$internal$core$server$bundler$Bundler_ts$default.bundleManifest (project-rome/@internal/core/server/bundler/Bundler.ts:315:22)
  12. Object.callback (project-rome/@internal/core/server/commands/bundle.ts:42:28)
  13. ___R$project$rome$$internal$core$server$Server_ts$default.dispatchRequest (project-rome/@internal/core/server/Server.ts:902:4)
  14. ___R$project$rome$$internal$core$server$Server_ts$default.handleRequest (project-rome/@internal/core/server/Server.ts:759:46)
  15. <anonymous> (project-rome/@internal/core/server/Server.ts:582:10)
  16. Function.all
  17. ___R$project$rome$$internal$events$Event_ts$default.call (project-rome/@internal/events/Event.ts:87:15)
  18. ___R$project$rome$$internal$events$Bridge_ts$default.handleMessageRequest (project-rome/@internal/events/Bridge.ts:582:3)
  19. ___R$project$rome$$internal$events$Bridge_ts$default.handleMessage (project-rome/@internal/events/Bridge.ts:539:4)

  ⚠ This diagnostic was derived from an internal Rome error. Potential bug, please report if necessary.

```

## Expected Results

It should build without errors

@sebmck the reason why I am running this command is because the vendor we have is too old and it doesn't contain some code I really need, such as the handling of the new configuration `dependencies.exceptions`.

I wanted to add the invalid licenses that we have in our website in that configuration but I can't.

### PR DESCRIPTION
**Pull request by sebmck**
## Summary

Fixes #1321. We were passing an absolute path to the bundler which was causing a partial project to be loaded that only included `public-packages/rome`. Then we try to seed a dependency graph with it but all the other files aren't present.

Typically if there's a `findProject` or some other operation done that indicates the desire to have a full project available then we then load it then. The bundler doesn't have such signal, and although we could just call one of those assumed methods to initialize it, I thought it would be clearer to add a new resolution option for entry resolutions.

## Test Plan

Ran `./rome run scripts/commit-rome.ts`.

### CODE REVIEW

File: internal/core/server/fs/Resolver.ts [hunk 1]
```diff
@@ -370,8 +374,12 @@ export default class Resolver {
 	}
 
 	private async maybeResolveEntryWithoutFileSystem(
-		query: ResolverRemoteQuery,
+		query: ResolverEntryQuery,
 	): Promise<undefined | ResolverQueryResponseFound> {
+		if (query.allowPartial === false) {
+			return undefined;
+		}
```
Comment (sebmck) [inline internal/core/server/fs/Resolver.ts:381]: And this are the actual only fixes. The rest are just some cleanup.
