### PR TITLE
fix: exit server process when daemon is stopped

### LINKED ISSUE #1528: 🐛 Stop command doesn't fully stop the rome daemon
## Environment

<details>
<summary>$ rome rage --summary</summary>

```
Environment Variables
  {COLORTERM: "truecolor", LANG: "en_US.UTF-8", TERM: "xterm-256color", TERM_PROGRAM: "vscode"}

User Config
  unset

Rome Version
  10.0.7-beta.18

Node Version
  14.17.0

Platform
  darwin x64 19.6.0

Terminal Features
  {
    background: "unknown"
    colorDepth: 24
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<150>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</Users/Yasser/Dev/rome>
    realCwd: AbsoluteFilePath</Users/Yasser/Dev/rome>
  }
```
</details>

## Steps To Reproduce

1. `./rome start`
```
ℹ No running daemon found. Starting one...
✔ Connected to daemon
✔ Started daemon!
```
2. `./rome stop`
```
✔ Connected to daemon
✔ Stopped server.
```
3. `./rome status`
```
✔ Connected to daemon
```
The `rome-server` process is still running and listening to the socket so the client connects to it, but the Server has mostly ended so it can't respond to requests.

Looks like the `socketServer` doesn't get attached as a resource so it doesn't get released when the Server ends. Also, I think we need to add a `safeProcessExit` to the stop command.

## Expected Results

After stopping the daemon, running `./rome status` should result in `✖ Server not running.`

### PR DESCRIPTION
**Pull request by yassere**
## Summary

Closes #1528 

  - Adds the socketServer as a resource so that it gets cleaned up when the server ends. 
  - Adds a `safeProcessExit(0)` to the server stop command. (Is this the right approach?)
  - Prevents a started daemon from inheriting stdio from the client.

## Test Plan

Manually tested.

`./rome start`
```
ℹ No running daemon found. Starting one...
✔ Connected to daemon
✔ Started daemon!
```
`./rome stop`
```
✔ Connected to daemon
✔ Stopped server.
```
`./rome status`
```
✖ Server not running.
```

### CODE REVIEW

File: internal/resources/factories.ts [hunk 1]
```diff
@@ -142,7 +142,7 @@ export function createResourceFromServer(server: net.Server, name: string = "net
     finalize: () => {
       return new Promise((resolve, reject) => {
         server.close((err) => {
-          if (err === undefined) {
+          if (err !== undefined) {
```
Comment (sebmck) [inline internal/resources/factories.ts:145]: Actually shouldn't this be:

```suggestion
          if (err != null) {
```

**Review by sebmck — APPROVED** [review]
Looks good!

File: internal/core/server/commands/stop.ts [hunk 2]
```diff
@@ -20,5 +21,6 @@ export default createServerCommand({
 	},
 	async callback({server}: ServerRequest) {
 		await server.end();
+		safeProcessExit(0);
```
Comment (jamiebuilds) [inline internal/core/server/commands/stop.ts:24]: Should this not be `await`'d?
