### PR TITLE
fix(rome_js_formatter): empty statements in `if/else` and `do/while`

### LINKED ISSUE #2448: 🐛 loop/if with empty statement body
### Environment information

```bash
WSL (W11/Ubuntu)
Yarn 3.2.0
```

### What happened?

1. Create project using yarn 3.2.0
2. Install Rome 
3. Run `yarn format` (`rome format .`)
4. Rerun `yarn`
```
project$ yarn format
Formatted x files in xms

project$ yarn
project/.yarn/releases/yarn-3.2.0.cjs:37184
                                                !e && !this.buffer.length && !this[sA] && this.emit("drain");
                                                ^

SyntaxError: Unexpected token '!'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

```

### Expected result

Rome should correctly format cjs without breaking it or not touch cjs at all.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Closes #2448

I cherry-picked the implementation of the former PR, which aligns its behaviour to prettier. 

The PR changes how `if/else` and `do/while` statements are formatted where the body is an empty statement, by matching Prettier's behaviour:

```js
// before
if(a); else ;

// now
if (a);
else;
```

## Test Plan

New tests to cover the case

### CODE REVIEW

**Comment by MichaReiser** [comment]
It would help reviewers to add some more context to the PR summary. How does it format empty statements differently than before, in what cases. I otherwise have to open the issue, read through all the discussions or infer the logic from your changes which makes it hard to tell if the logic is working as intended.

File: crates/rome_js_formatter/src/js/statements/do_while_statement.rs [hunk 1]
```diff
@@ -39,12 +39,19 @@ impl FormatNode for JsDoWhileStatement {
...
+                space_token(),
                 body.format(formatter)?,
                 tail,
             ]))
+        } else if matches!(body, JsAnyStatement::JsEmptyStatement(_)) {
+            Ok(format_elements![
+                hard_group_elements(format_elements![head, body.format(formatter)?,]),
+                hard_line_break(),
+                tail,
+            ])
```
Comment (yassere) [inline crates/rome_js_formatter/src/js/statements/do_while_statement.rs:51]: The `tail` here isn't inside a hard group, so this would reposition a block comment from:

```js
do;
while /* comment */ (true); 
```
To:
```js
do;
while (true); /* comment */
```
Speaking of hard groups, I'm not sure why `JsBlockStatement` requires special grouping here. Would this work for everything except `JsEmptyStatement`?
```rs
hard_group_elements(format_elements![
    head,
    space_token(),
    body.format(formatter)?,
    tail,
])
```

Comment (yassere) [reply crates/rome_js_formatter/src/js/statements/do_while_statement.rs:51]: Actually, PR #2597 removes hard groups, so this comment will be out of date once that merges. Looks like inline block comments will be addressed later.

**Comment by ematipico** [comment]
> It would help reviewers to add some more context to the PR summary. How does it format empty statements differently than before, in what cases. I otherwise have to open the issue, read through all the discussions or infer the logic from your changes which makes it hard to tell if the logic is working as intended.

I updated the description with a brief example of the changes.

**Comment by ematipico** [comment]
> Looks good. Would you mind generating the prettier report and posting how the metric changes with your PR?

PR 
```
**File Based Average Prettier Similarity**: 70.84%  
**Line Based Average Prettier Similarity**: 64.85% 
```

`main`
```
**File Based Average Prettier Similarity**: 70.80%  
**Line Based Average Prettier Similarity**: 64.83%  
```
