### PR TITLE
fix(rome_cli): improve the logging of panics and connection errors

### LINKED ISSUE #3920: 🐛 "Rome client: couldn't create connection to server" error when starting VSCode with Rome extension installed
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   linux

Workspace:
  Open Documents:       0

Rome Server Log:

⚠ Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code
```

### What happened?

It randomly happens that the VSCode extension runs into the following error:

```
[Error - 12:19:39 PM] Rome client: couldn't create connection to server.
RangeError: Port should be >= 0 and < 65536. Received .
	at new NodeError (node:internal/errors:371:5)
	at validatePort (node:internal/validators:217:11)
	at lookupAndConnect (node:net:1013:5)
	at Socket.connect (node:net:989:5)
	at connect (node:net:203:17)
	at createMessageTransports (/home/markus/.vscode/extensions/rome.rome-0.18.1-linux-x64/out/main.js:18289:41)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async LanguageClient2.createConnection (/home/markus/.vscode/extensions/rome.rome-0.18.1-linux-x64/out/main.js:15294:28)
	at async LanguageClient2.start (/home/markus/.vscode/extensions/rome.rome-0.18.1-linux-x64/out/main.js:14892:30)
```

### Expected result

Rome client doesn't crash

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by leops**
## Summary

Fixes #3920

This is a followup to #3952 adding additional logs to the CLI and VSCode extension. Specifically, it extends the panic hook of the CLI to print the panic message to the current tracing log file in addition to stderr. This ensures that panic messages can be retrieved in the logs when they cause a background process like the language server to crash.

In addition to this, I extended the previous changes to the VSCode extension to wrap errors thrown by the `connect` function in addition to the exceptions raised by the socket itself. I also improved the `getSocket` function by collecting the content of the stderr pipe for the CLI child process in addition to stdout, and to fail with an error if the content of stdout was empty. This error will now include the exit code of the CLI as well as the content of stderr if it was not empty.

## Test Plan

I tested these changes locally by introducing explicit panics in the `print_socket` and `run_daemon` functions to ensure that the panic is correctly getting logged to the tracing log file, and that the extension correctly prints the content of stderr if the CLI instance exits with an error.

### CODE REVIEW

File: editors/vscode/src/main.ts [hunk 1]
```diff
@@ -258,41 +258,61 @@ function getSocket(
...
+				if (stderr.length > 0) {
+					message += `\nOutput:\n${stderr}`;
+				}
+
+				reject(new Error(message));
+				return;
 			}
+
+			outputChannel.appendLine(`Connecting to "${pipeName}" ...`);
+			resolve(pipeName);
```
Comment (ematipico) [inline editors/vscode/src/main.ts:285]: nit: I would prefer the `if`/`else` here because it's safer. We don't have a lint rule that catches the possible absence of an early return.

**Review by ematipico — APPROVED** [review]

**Comment by MichaReiser** [comment]
Fixes #3920
