### PR TITLE
fix(rome_js_analyze): handle default clause in `useSingleCaseStetement`

### LINKED ISSUE #4068: 📎 `useSingleCaseStatement` should handle `default` clauses
### Description

`useSIngleCasStatement` should report the following code:

```js
switch (foo) {
	case true:
	default:
		let foo = "";
		foo;
}
```

For now, the rule only handles `case` clauses. While it is consistent with its name, it certainly was not the intent of the rule.

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Closes #4068.
I also updated the diagnostic for better consistency with other rules.

By the way, the rule should certainly be renamed to `useSingleSwitchClauseStatement`.
Unfortunately, this is a stable rule.

I personally could rather deprecate the rule, once [`noSwitchDeclarations`](https://github.com/rome/tools/pull/3917) becomes merged or stable.

## Test Plan

New Unit test for `default` switch clauses.

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

### CODE REVIEW

File: crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs [hunk 1]
```diff
@@ -47,104 +45,59 @@ declare_rule! {
...
+        let switch_clause = ctx.query();
+        let clause_token = switch_clause.clause_token().ok()?;
+        let colon_token = switch_clause.colon_token().ok()?;
+        let consequent = switch_clause.consequent();
+        // Do not handle cases where spaces and tabs are mixed
+        let indentation = clause_token
+            .leading_trivia()
+            .pieces()
+            .filter(|x| x.is_newline() || x.is_whitespace())
+            .take(2);
```
[the remark this answers is not in the document]
Comment (Conaclos) [reply crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs:83]: > Stopping at the first 2 leading trivia pieces will only work if the file is using tab indentation and the switch statement is not nested, for instance applying the code action will result in incorrect indentation in this case:

Contiguous tabs/spaces form a single trivia.
e.g. `DEFAULT_KW@124..145 "default" [Newline("\n"), Whitespace("    \t  ")] []`.
However, I accept that this is a hack: nothing ensures that contiguous tabs/spaces always form a single trivia.
Moreover, other trivia (e.g. comments) produce issues.

> To avoid this kind of regression I would advice against modifying existing snapshots

I accept. In fact, the change was not intentional: automatic formatting of the input file with prettier.

[the remark this answers is not in the document]
Comment (Conaclos) [reply crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs]: @leops
I added the function `indentation_trivia` in `rome::rowan` crate.

File: crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs [hunk 2]
```diff
@@ -47,104 +45,53 @@ declare_rule! {
...
+        let clause_token = switch_clause.clause_token().ok()?;
+        let colon_token = switch_clause.colon_token().ok()?;
+        let consequent = switch_clause.consequent();
+        let new_colon_token = colon_token.with_trailing_trivia(iter::empty());
+        let new_consequent = make::js_statement_list(Some(AnyJsStatement::JsBlockStatement(
+            make::js_block_statement(
+                make::token(T!['{'])
+                    .with_leading_trivia(Some((TriviaPieceKind::Whitespace, " ")))
+                    .with_trailing_trivia_pieces(colon_token.trailing_trivia().pieces()),
+                consequent.to_owned(),
```
Comment (ematipico) [inline crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs:84]: `.clone()` is preferred here

File: crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs [hunk 3]
```diff
@@ -47,104 +45,53 @@ declare_rule! {
...
+                make::token(T!['}']).with_leading_trivia_pieces(clause_token.indentation_trivia()),
```
Comment (ematipico) [inline crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs:85]: Nit: I wonder if `indentation_trivia` could return an iterator instead (via `chain_pieces`). This would prevent allocating a new vector.

**Review by ematipico — APPROVED** [review]

File: crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs (hunk 3 above)
Comment (Conaclos) [reply crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs:85]: I have some hard time with trivia handling. 

`chain_trivia_pieces` requires two pieces. Do ypu suggest using an empty trivia piece as second parameter?

By the way, `indentation_trivia` filter out comments and unknown trivia, this makes the iterator not exact.

Comment (Conaclos) [reply crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs:85]: I found a way for avoiding the allocation :)

**Review by ematipico — APPROVED** [review]
