### PR TITLE
fix(rome_js_semantic): correct the export determination when a variable and an `interface` had the same name

### LINKED ISSUE #4353: 🐛 `noUnusedVariables` fails to detect class exports if there is an interface with the same name as the exported class
### Environment information

```block
CLI:
  Version:                      12.0.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.12.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.2.0"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true

Workspace:
  Open Documents:               0

Discovering running Rome servers...
```

### What happened?

Minimal reproduction:
```ts
class MyClass {}

interface MyClass {
    foo: string;
}

export { MyClass };
```
image

It works fine without the `interface`:
```ts
class MyClass {}

export { MyClass };
```
image

### Expected result

It should not throw an error.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by unvalley**
## Summary

Closes #4353 

## Test Plan

`cargo test -p rome_js_analyze -- no_unused_variables`

## Changelog

- [x] The PR requires a changelog line

## Documentation

- ~[ ] The PR requires documentation~
- ~[ ] I will create a new PR to update the documentation~

### CODE REVIEW

File: crates/rome_js_semantic/src/events.rs [hunk 1]
```diff
@@ -616,38 +623,77 @@ impl SemanticEventExtractor {
...
+                                declared_at: declaration_at,
                                 scope_id: scope.scope_id,
                             },
                         };
                         self.stash.push_back(e);
 
                         match reference {
-                            Reference::Read { is_exported, .. } if is_exported => {
+                            Reference::Read { is_exported, .. } if *is_exported => {
+                                let find_exportable_declration = scope.shadowed.iter().find_map(
```
Comment (unvalley) [inline crates/rome_js_semantic/src/events.rs:659]: We need to access the `scope.shadowed` to find a variable or an interface already shadowed. An interface may be declared before an variable declaration.

```ts
class A {} 

interface A { // Here, the class A is shadowed 
	foo: string;
}

export { A };
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -7,6 +7,9 @@
 ### Editors
 ### Formatter
 ### Linter
+
+- Fix an issue that [`noUnusedVariables`](https://docs.rome.tools/lint/rules/nounusedvariables/) rule did not correctly detect exports when a variable and an `interface` had the same name [#4468](https://github.com/rome/tools/pull/4468)
```
Comment (ematipico) [inline CHANGELOG.md:11]: You should add the `#### Other changes` heading

File: crates/rome_js_semantic/src/events.rs [hunk 3]
```diff
@@ -154,14 +154,20 @@ impl SemanticEvent {
...
     scopes: Vec<Scope>,
     next_scope_id: usize,
     /// At any point this is the set of available bindings and
     /// the range of its declaration
-    bindings: FxHashMap<SyntaxTokenText, TextRange>,
+    bindings: FxHashMap<SyntaxTokenText, DeclaredBinding>,
+}
+
+#[derive(Debug)]
+struct DeclaredBinding {
```
Comment (ematipico) [inline crates/rome_js_semantic/src/events.rs:168]: Could you add a brief documentation of the struct, please?

File: crates/rome_js_semantic/src/events.rs [hunk 4]
```diff
@@ -747,16 +792,22 @@ impl SemanticEventExtractor {
...
         // insert this name into the list of available names
         // and save shadowed names to be used later
         let shadowed = self
             .bindings
-            .insert(name.clone(), declaration_range)
+            .insert(
+                name.clone(),
+                DeclaredBinding {
+                    text_range: declaration_range,
+                    syntax_kind: *parent_syntax_kind,
```
Comment (ematipico) [inline crates/rome_js_semantic/src/events.rs:808]: The name `syntax_kind` is a bit misleading because I thought we were saving the syntax kind of the node, but instead, we are passing the **parent** syntax kind. Should we change the name and document it a bit **why** we save the parent syntax kind?

Comment (ematipico) [reply crates/rome_js_semantic/src/events.rs]: Sounds good to me!

File: crates/rome_js_semantic/src/events.rs (hunk 1 above)
Comment (Conaclos) [reply crates/rome_js_semantic/src/events.rs:663]: This could be worth adding this comment in the code?

Comment (unvalley) [reply crates/rome_js_semantic/src/events.rs:664]: I added more comments! [c80655b](https://github.com/rome/tools/pull/4468/commits/c80655b59d2a170de643cebbe6a2c0d2b16868af)

**Review by ematipico — APPROVED** [review]
