### PR TITLE
fix(rome_js_parser): Better error recover for jsx attribute #2944

### LINKED ISSUE #2944: 🐛 Unfriendly error messages for syntax errors inside jsx
### Environment information

[Playground](https://play.rome.tools/?code=function+foo%28%29+%7B%0A++return+%28%0A++++%3Cdiv+className%3D%7Basdf+asdf%7D+%2F%3E%0A++%29%3B%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=true&jsx=true#ZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAZABpAHYAIABjAGwAYQBzAHMATgBhAG0AZQA9AHsAYQBzAGQAZgAgAGEAcwBkAGYAfQAgAC8APgAKACAAIAApADsACgB9AA==)

### What happened?

For syntax errors inside jsx, Rome will output a lot of unfriendly error messages and even code fixes.

For example, 
```
function foo() {
  return (
    <div className={asdf asdf} />
  );
}
```

will give you
```
error[SyntaxError]: expected `}` but instead found `asdf`
  ┌─ main.js:3:26
  │
3 │     <div className={asdf asdf} />
  │                          ^^^^ unexpected

error[SyntaxError]: expected a JSX attribute but instead found '}'
  ┌─ main.js:3:30
  │
3 │     <div className={asdf asdf} />
  │                              ^ Expected a JSX attribute here

error[SyntaxError]: expected `<` but instead the file ends
  ┌─ main.js:5:2
  │
5 │ }
  │  ^ the file ends here

error: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
  ┌─ main.js:3:30
  │
3 │     <div className={asdf asdf} />
  │                              ^

error: Unexpected token. Did you mean `{'>'}` or `&gt;`?
  ┌─ main.js:3:33
  │
3 │     <div className={asdf asdf} />
  │                                 ^

error: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
  ┌─ main.js:5:1
  │
5 │ }
  │ ^

warning[[jsx/noImplicitBoolean](https://rome.tools/docs/lint/rules/noImplicitBoolean/)]: Use explicit boolean values for boolean JSX props.
  ┌─ main.js:3:26
  │
3 │     <div className={asdf asdf} />
  │                          ----

Safe fix: Add explicit `true` literal for this attribute
    | @@ -1,5 +1,5 @@
0 0 |   function foo() {
1 1 |     return (
2   | -     <div className={asdf asdf} />
  2 | +     <div className={asdf asdf={true}} />
3 3 |     );
4 4 |   }
```

### Expected result

I'm expecting the syntax error to be contained inside the boundary of `{}` (JsxExpression), and see no other jsx errors.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
1. Resolved #2944

## Test Plan
1. Should pass all test cases newly added.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
!bench_parser

File: crates/rome_js_analyze/tests/specs/jsx/noImplicitBoolean.jsx.snap [hunk 1]
```diff
@@ -10,6 +11,8 @@ expression: noImplicitBoolean.jsx
 <input disabled={0} />;
 <input disabled={undefined} />;
 <input disabled="false" />;
+// https://github.com/rome/tools/issues/2944
+<div className={asdf asdf} />;
```
Comment (MichaReiser) [inline crates/rome_js_analyze/tests/specs/jsx/noImplicitBoolean.jsx.snap:15]: Can you add a formatter test as well. I'm interested to see how well skipped token trivia work

File: crates/rome_js_parser/src/syntax/jsx/mod.rs [hunk 2]
```diff
@@ -614,7 +615,17 @@ fn parse_jsx_expression_attribute_value(p: &mut Parser) -> ParsedSyntax {
...
+        p.eat(T!['}']);
+    } else {
+        p.error(expected_token(T!['}']));
+        p.parse_as_skipped_trivia_tokens(|p| {
+            while !p.at_ts(token_set![T!['}'], T![EOF]]) {
+                p.bump_any();
+            }
+        });
+        p.expect(T!['}']);
+    }
```
Comment (MichaReiser) [inline crates/rome_js_parser/src/syntax/jsx/mod.rs:628]: I think just eating over any token until the end of the file may make things worse, for example if you have:

```
<div className={asdf>test</div>
                                   ^- cursor position
```

I would recommend to test if the next token is a `}` and only then use this recovery path

```suggestion
    if !p.expect(T!['}']) {
        if p.nth_at(T!['}']) {
           p.parse_as_skipped_trivia_tokens(|p| {
       	    	p.bump_any();
        	});
        }
    }
```

**Review by MichaReiser — COMMENTED** [review]
Nice, thanks for working on this fix!

File: crates/rome_js_analyze/tests/specs/jsx/noImplicitBoolean.jsx.snap (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_analyze/tests/specs/jsx/noImplicitBoolean.jsx.snap:15]: Done

**Review by MichaReiser — APPROVED** [review]

**Comment by MichaReiser** [comment]
Awesome. Can you take a look at the failing test. It should then be ready to merge.

**Comment by IWANABETHATGUY** [comment]
> Awesome. Can you take a look at the failing test. It should then be ready to merge.

The formatter test case need some tweak

**Comment by IWANABETHATGUY** [comment]
!bench_formatter

File: crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs [hunk 3]
```diff
@@ -70,7 +70,19 @@ impl FormatNodeRule<JsxExpressionAttributeValue> for FormatJsxExpressionAttribut
...
+                // <div className={asdf asdf} />;
+                let r_curly_token_ref = r_curly_token.as_ref()?;
+                if matches!(
+                    r_curly_token_ref.leading_trivia().first().map(|t| t.kind()),
+                    Some(TriviaPieceKind::Skipped)
+                ) {
+                    write!(f, [space_token(), r_curly_token.format()])
+                } else {
+                    write!(f, [r_curly_token.format()])
+                }
```
Comment (MichaReiser) [inline crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs:85]: This wont be working if you have something like

```
<div className={asdf /* comment */ asdf} />
```

what happens without this special case handling?

Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs:85]:
```jsx
<div className={asdf asdf} />
```
will be formatted to: 
```jsx
<div className={asdfasdf} />
```

Comment (MichaReiser) [reply crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs:85]: Yeah, that makes sense... This isn't ideal. You can probably to

```
let needs_space_separator = r_curly_token_ref.leading_trivia().skip_while(|t| t.is_newline() || t.is_whitespace().first().map_or(false, |p| p.is_skipped); 

if needs_space_separator {
	write!(f, [space_token()])?;
}

write!(f, [r_curly_token.format()])?;
```

But it's probably worth to add one more test where there's also a comment between the skipped and `r_curly_token` trivia

Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs:85]: Done

Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs:85]: The current implementation is good enough because garbage in garbage out, what do you think?

File: crates/rome_js_formatter/tests/specs/jsx/attributes.jsx [hunk 4]
```diff
@@ -43,3 +43,8 @@
 
 					<test {...WithAVeryLongFunctionthat_exceeds_the_line_width_what_happens_with_ithis()} />;
 					<div {...["Chungking Express", "Fallen Angels", "In the Mood for Love", "Days of Living Wild", "Happy Together"]}/>;
+
+
+//  https://github.com/rome/tools/issues/2944
+<div className={asdf asdf} />;
+<div className={asdf /** test*/ asdf} />;
```
Comment (MichaReiser) [inline crates/rome_js_formatter/tests/specs/jsx/attributes.jsx:50]: Sorry, I should have given a better example. This comment is a trailing comment and has no effect on your formatting logic. Can you try

```
<div className={asdf
	/* comment */ asdf } />
```

File: crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs (hunk 3 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs]: > 

`leading_trivia()` will not return an iterator, am I missing something?

File: crates/rome_js_formatter/tests/specs/jsx/attributes.jsx (hunk 4 above)
Comment (IWANABETHATGUY) [reply crates/rome_js_formatter/tests/specs/jsx/attributes.jsx:50]: Is that alright? 
```jsx
<div
	className={
		asdf
	/* comment */asdf }
/>;
```
